export default function AboutPage() {
  return (
    <div className="min-h-screen bg-stone-100 text-stone-900">
      <header className="bg-stone-800 text-stone-100 px-4 py-4">
        <div className="container mx-auto">
          <a href="/lang/Russian" className="text-xl font-bold hover:text-stone-300">
            ← Back to Game
          </a>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <h1 className="text-4xl font-bold mb-6 text-stone-800">About This Game</h1>

        <div className="bg-white rounded-lg p-6 shadow-md space-y-6">
          <section>
            <h2 className="text-2xl font-bold mb-3 text-stone-800">Built with Vercel</h2>
            <p className="text-stone-700 mb-3">
              This language learning game was created using{" "}
              <a href="https://vercel.com" className="text-blue-600 hover:underline">
                Vercel
              </a>
              , a platform for frontend developers that provides the best developer experience for building web
              applications.
            </p>
            <p className="text-stone-700">
              Vercel enables developers to deploy websites and applications with zero configuration, automatic SSL,
              instant cache invalidation, and more. It's the platform behind popular frameworks like Next.js.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3 text-stone-800">Vibe Coding</h2>
            <p className="text-stone-700 mb-3">
              This game demonstrates the concept of "vibe coding" - creating applications through conversational AI
              without writing traditional code. The entire application was generated by describing what we wanted in
              natural language to an AI assistant.
            </p>
            <p className="text-stone-700">
              This approach democratizes software development, allowing anyone with an idea to bring it to life without
              years of programming experience.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3 text-stone-800">Learning Opportunity</h2>
            <p className="text-stone-700 mb-3">
              This site serves as an excellent base for learning about AI-assisted development. You can:
            </p>
            <ul className="list-disc list-inside space-y-2 text-stone-700">
              <li>Explore how AI interprets requirements and generates code</li>
              <li>Modify the prompts to create variations (different languages, topics, difficulty levels)</li>
              <li>Learn about Progressive Web Apps (PWA) and offline-first design</li>
              <li>Understand modern web technologies like React, Next.js, and TypeScript</li>
              <li>Experiment with drag-and-drop interactions and game mechanics</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3 text-stone-800">Customization Ideas</h2>
            <p className="text-stone-700 mb-3">Fork this project to create your own version:</p>
            <ul className="list-disc list-inside space-y-2 text-stone-700">
              <li>Change to different languages (Spanish, French, Mandarin, etc.)</li>
              <li>Use different quote sources (movies, songs, technical terms)</li>
              <li>Add difficulty levels or timed challenges</li>
              <li>Create multiplayer competitions</li>
              <li>Add achievements and badges</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3 text-stone-800">Open Source</h2>
            <p className="text-stone-700">
              Check the{" "}
              <a href="/lang/Russian/open-source" className="text-blue-600 hover:underline">
                Open Source
              </a>{" "}
              page to see the exact prompt used to create this game. You can use it as a starting point for your own
              projects!
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
