export type Phrase = {
  english: string
  russian: string
  source: string
  wordTranslations: Record<string, string>
}

export const PHRASES: Phrase[] = [
  // Quran (15)
  {
    english: "In the name of God, the Most Gracious, the Most Merciful",
    russian: "Во имя Аллаха милостивого милосердного",
    source: "—The Quran",
    wordTranslations: { Во: "in", имя: "name", Аллаха: "Allah", милостивого: "gracious", милосердного: "merciful" },
  },
  {
    english: "Indeed, with hardship comes ease",
    russian: "Поистине с трудностью приходит лёгкость",
    source: "—The Quran",
    wordTranslations: { Поистине: "indeed", с: "with", трудностью: "hardship", приходит: "comes", лёгкость: "ease" },
  },
  {
    english: "And He is with you wherever you are",
    russian: "И Он с вами где бы вы ни были",
    source: "—The Quran",
    wordTranslations: {
      И: "and",
      Он: "He",
      с: "with",
      вами: "you",
      где: "where",
      бы: "ever",
      вы: "you",
      ни: "not",
      были: "are",
    },
  },
  {
    english: "God does not burden a soul beyond what it can bear",
    russian: "Аллах не возлагает на душу сверх её возможностей",
    source: "—The Quran",
    wordTranslations: {
      Аллах: "Allah",
      не: "not",
      возлагает: "burden",
      на: "on",
      душу: "soul",
      сверх: "beyond",
      её: "its",
      возможностей: "capacity",
    },
  },
  {
    english: "Seek help through patience and prayer",
    russian: "Ищите помощь через терпение и молитву",
    source: "—The Quran",
    wordTranslations: {
      Ищите: "seek",
      помощь: "help",
      через: "through",
      терпение: "patience",
      и: "and",
      молитву: "prayer",
    },
  },
  {
    english: "The truth has come and falsehood has vanished",
    russian: "Истина пришла и ложь исчезла",
    source: "—The Quran",
    wordTranslations: { Истина: "truth", пришла: "came", и: "and", ложь: "falsehood", исчезла: "vanished" },
  },
  {
    english: "Remember Me and I will remember you",
    russian: "Помните Меня и Я вспомню вас",
    source: "—The Quran",
    wordTranslations: { Помните: "remember", Меня: "Me", и: "and", Я: "I", вспомню: "remember", вас: "you" },
  },
  {
    english: "Verily, God is with those who are patient",
    russian: "Воистину Аллах с теми кто терпелив",
    source: "—The Quran",
    wordTranslations: { Воистину: "verily", Аллах: "Allah", с: "with", теми: "those", кто: "who", терпелив: "patient" },
  },
  {
    english: "And speak to people with kindness",
    russian: "И говорите людям с добротой",
    source: "—The Quran",
    wordTranslations: { И: "and", говорите: "speak", людям: "people", с: "with", добротой: "kindness" },
  },
  {
    english: "God is the Light of the heavens and the earth",
    russian: "Аллах свет небес и земли",
    source: "—The Quran",
    wordTranslations: { Аллах: "Allah", свет: "light", небес: "heavens", и: "and", земли: "earth" },
  },
  {
    english: "So verily, with hardship comes ease",
    russian: "Так воистину с трудностью приходит лёгкость",
    source: "—The Quran",
    wordTranslations: {
      Так: "so",
      воистину: "verily",
      с: "with",
      трудностью: "hardship",
      приходит: "comes",
      лёгкость: "ease",
    },
  },
  {
    english: "Do good and good will come to you",
    russian: "Делайте добро и добро придёт к вам",
    source: "—The Quran",
    wordTranslations: { Делайте: "do", добро: "good", и: "and", добро: "good", придёт: "come", к: "to", вам: "you" },
  },
  {
    english: "Be patient, for God is with the patient",
    russian: "Будьте терпеливы ибо Аллах с терпеливыми",
    source: "—The Quran",
    wordTranslations: {
      Будьте: "be",
      терпеливы: "patient",
      ибо: "for",
      Аллах: "Allah",
      с: "with",
      терпеливыми: "patient",
    },
  },
  {
    english: "The best of people are those most beneficial to others",
    russian: "Лучшие из людей те кто наиболее полезен другим",
    source: "—The Quran",
    wordTranslations: {
      Лучшие: "best",
      из: "of",
      людей: "people",
      те: "those",
      кто: "who",
      наиболее: "most",
      полезен: "beneficial",
      другим: "others",
    },
  },
  {
    english: "And whoever saves a life, it is as though he had saved all of mankind",
    russian: "И кто спасёт жизнь это как будто он спас всё человечество",
    source: "—The Quran",
    wordTranslations: {
      И: "and",
      кто: "whoever",
      спасёт: "saves",
      жизнь: "life",
      это: "it",
      как: "as",
      будто: "though",
      он: "he",
      спас: "saved",
      всё: "all",
      человечество: "mankind",
    },
  },

  // Bible (15)
  {
    english: "In the beginning God created the heaven and the earth",
    russian: "В начале Бог сотворил небо и землю",
    source: "—The Bible",
    wordTranslations: {
      В: "in",
      начале: "beginning",
      Бог: "God",
      сотворил: "created",
      небо: "heaven",
      и: "and",
      землю: "earth",
    },
  },
  {
    english: "Let there be light",
    russian: "Да будет свет",
    source: "—The Bible",
    wordTranslations: { Да: "let", будет: "be", свет: "light" },
  },
  {
    english: "Love thy neighbor as thyself",
    russian: "Возлюби ближнего своего как самого себя",
    source: "—The Bible",
    wordTranslations: { Возлюби: "love", ближнего: "neighbor", своего: "thy", как: "as", самого: "thy", себя: "self" },
  },
  {
    english: "Do unto others as you would have them do unto you",
    russian: "Поступай с другими так как хочешь чтобы они поступали с тобой",
    source: "—The Bible",
    wordTranslations: {
      Поступай: "do",
      с: "unto",
      другими: "others",
      так: "as",
      как: "as",
      хочешь: "would",
      чтобы: "have",
      они: "them",
      поступали: "do",
      с: "unto",
      тобой: "you",
    },
  },
  {
    english: "The Lord is my shepherd, I shall not want",
    russian: "Господь пастырь мой я ни в чём не нуждаюсь",
    source: "—The Bible",
    wordTranslations: {
      Господь: "Lord",
      пастырь: "shepherd",
      мой: "my",
      я: "I",
      ни: "not",
      в: "in",
      чём: "what",
      не: "not",
      нуждаюсь: "want",
    },
  },
  {
    english: "For God so loved the world",
    russian: "Ибо так возлюбил Бог мир",
    source: "—The Bible",
    wordTranslations: { Ибо: "for", так: "so", возлюбил: "loved", Бог: "God", мир: "world" },
  },
  {
    english: "Ask and it shall be given unto you",
    russian: "Просите и дано будет вам",
    source: "—The Bible",
    wordTranslations: { Просите: "ask", и: "and", дано: "given", будет: "shall be", вам: "you" },
  },
  {
    english: "Blessed are the peacemakers",
    russian: "Блаженны миротворцы",
    source: "—The Bible",
    wordTranslations: { Блаженны: "blessed", миротворцы: "peacemakers" },
  },
  {
    english: "The truth shall set you free",
    russian: "Истина освободит вас",
    source: "—The Bible",
    wordTranslations: { Истина: "truth", освободит: "set free", вас: "you" },
  },
  {
    english: "Faith can move mountains",
    russian: "Вера может двигать горы",
    source: "—The Bible",
    wordTranslations: { Вера: "faith", может: "can", двигать: "move", горы: "mountains" },
  },
  {
    english: "Man does not live by bread alone",
    russian: "Не хлебом единым жив человек",
    source: "—The Bible",
    wordTranslations: { Не: "not", хлебом: "bread", единым: "alone", жив: "live", человек: "man" },
  },
  {
    english: "There is a time for everything",
    russian: "Всему своё время",
    source: "—The Bible",
    wordTranslations: { Всему: "everything", своё: "its", время: "time" },
  },
  {
    english: "Love is patient, love is kind",
    russian: "Любовь терпелива любовь добра",
    source: "—The Bible",
    wordTranslations: { Любовь: "love", терпелива: "patient", любовь: "love", добра: "kind" },
  },
  {
    english: "The meek shall inherit the earth",
    russian: "Кроткие наследуют землю",
    source: "—The Bible",
    wordTranslations: { Кроткие: "meek", наследуют: "inherit", землю: "earth" },
  },
  {
    english: "Judge not lest ye be judged",
    russian: "Не судите да не судимы будете",
    source: "—The Bible",
    wordTranslations: { Не: "not", судите: "judge", да: "lest", не: "not", судимы: "judged", будете: "be" },
  },

  // Talmud (15)
  {
    english: "Silence is a fence around wisdom",
    russian: "Молчание ограда вокруг мудрости",
    source: "—The Talmud",
    wordTranslations: { Молчание: "silence", ограда: "fence", вокруг: "around", мудрости: "wisdom" },
  },
  {
    english: "Who is wise? One who learns from every person",
    russian: "Кто мудр? Тот кто учится у каждого человека",
    source: "—The Talmud",
    wordTranslations: {
      Кто: "who",
      мудр: "wise",
      Тот: "one",
      кто: "who",
      учится: "learns",
      у: "from",
      каждого: "every",
      человека: "person",
    },
  },
  {
    english: "The day is short and the work is much",
    russian: "День короток а работа велика",
    source: "—The Talmud",
    wordTranslations: { День: "day", короток: "short", а: "and", работа: "work", велика: "much" },
  },
  {
    english: "Whoever saves one life saves the world entire",
    russian: "Кто спасает одну жизнь спасает весь мир",
    source: "—The Talmud",
    wordTranslations: {
      Кто: "whoever",
      спасает: "saves",
      одну: "one",
      жизнь: "life",
      спасает: "saves",
      весь: "entire",
      мир: "world",
    },
  },
  {
    english: "If I am not for myself, who will be for me?",
    russian: "Если я не за себя кто будет за меня?",
    source: "—The Talmud",
    wordTranslations: {
      Если: "if",
      я: "I",
      не: "not",
      за: "for",
      себя: "myself",
      кто: "who",
      будет: "will be",
      за: "for",
      меня: "me",
    },
  },
  {
    english: "Say little and do much",
    russian: "Говори мало и делай много",
    source: "—The Talmud",
    wordTranslations: { Говори: "say", мало: "little", и: "and", делай: "do", много: "much" },
  },
  {
    english: "Do not be daunted by the enormity of the world's grief",
    russian: "Не унывайте из-за огромности мирового горя",
    source: "—The Talmud",
    wordTranslations: {
      Не: "not",
      унывайте: "daunted",
      "из-за": "by",
      огромности: "enormity",
      мирового: "world's",
      горя: "grief",
    },
  },
  {
    english: "A person is judged by their deeds, not their words",
    russian: "Человека судят по делам а не по словам",
    source: "—The Talmud",
    wordTranslations: {
      Человека: "person",
      судят: "judged",
      по: "by",
      делам: "deeds",
      а: "not",
      не: "not",
      по: "by",
      словам: "words",
    },
  },
  {
    english: "Make your books your companions",
    russian: "Сделайте книги своими спутниками",
    source: "—The Talmud",
    wordTranslations: { Сделайте: "make", книги: "books", своими: "your", спутниками: "companions" },
  },
  {
    english: "Where there is no vision, the people perish",
    russian: "Где нет видения народ погибает",
    source: "—The Talmud",
    wordTranslations: { Где: "where", нет: "no", видения: "vision", народ: "people", погибает: "perish" },
  },
  {
    english: "The highest form of wisdom is kindness",
    russian: "Высшая форма мудрости это доброта",
    source: "—The Talmud",
    wordTranslations: { Высшая: "highest", форма: "form", мудрости: "wisdom", это: "is", доброта: "kindness" },
  },
  {
    english: "Do not look at the flask but at what it contains",
    russian: "Не смотри на сосуд а на то что он содержит",
    source: "—The Talmud",
    wordTranslations: {
      Не: "not",
      смотри: "look",
      на: "at",
      сосуд: "flask",
      а: "but",
      на: "at",
      то: "what",
      что: "what",
      он: "it",
      содержит: "contains",
    },
  },
  {
    english: "The reward of a good deed is another good deed",
    russian: "Награда за доброе дело это ещё одно доброе дело",
    source: "—The Talmud",
    wordTranslations: {
      Награда: "reward",
      за: "of",
      доброе: "good",
      дело: "deed",
      это: "is",
      ещё: "another",
      одно: "one",
      доброе: "good",
      дело: "deed",
    },
  },
  {
    english: "More than the calf wishes to suckle, the cow wishes to nurse",
    russian: "Больше чем телёнок хочет сосать корова хочет кормить",
    source: "—The Talmud",
    wordTranslations: {
      Больше: "more",
      чем: "than",
      телёнок: "calf",
      хочет: "wishes",
      сосать: "suckle",
      корова: "cow",
      хочет: "wishes",
      кормить: "nurse",
    },
  },
  {
    english: "Who is rich? One who is satisfied with their portion",
    russian: "Кто богат? Тот кто доволен своей долей",
    source: "—The Talmud",
    wordTranslations: {
      Кто: "who",
      богат: "rich",
      Тот: "one",
      кто: "who",
      доволен: "satisfied",
      своей: "their",
      долей: "portion",
    },
  },

  // US Bill of Rights (5)
  {
    english: "Congress shall make no law abridging the freedom of speech",
    russian: "Конгресс не должен принимать закон ограничивающий свободу слова",
    source: "—US Bill of Rights",
    wordTranslations: {
      Конгресс: "Congress",
      не: "no",
      должен: "shall",
      принимать: "make",
      закон: "law",
      ограничивающий: "abridging",
      свободу: "freedom",
      слова: "speech",
    },
  },
  {
    english: "The right of the people to keep and bear arms shall not be infringed",
    russian: "Право народа хранить и носить оружие не должно нарушаться",
    source: "—US Bill of Rights",
    wordTranslations: {
      Право: "right",
      народа: "people",
      хранить: "keep",
      и: "and",
      носить: "bear",
      оружие: "arms",
      не: "not",
      должно: "shall",
      нарушаться: "infringed",
    },
  },
  {
    english: "No person shall be deprived of life, liberty, or property without due process of law",
    russian: "Никто не может быть лишён жизни свободы или собственности без надлежащей правовой процедуры",
    source: "—US Bill of Rights",
    wordTranslations: {
      Никто: "no person",
      не: "not",
      может: "shall",
      быть: "be",
      лишён: "deprived",
      жизни: "life",
      свободы: "liberty",
      или: "or",
      собственности: "property",
      без: "without",
      надлежащей: "due",
      правовой: "law",
      процедуры: "process",
    },
  },
  {
    english: "Excessive bail shall not be required",
    russian: "Чрезмерный залог не должен требоваться",
    source: "—US Bill of Rights",
    wordTranslations: { Чрезмерный: "excessive", залог: "bail", не: "not", должен: "shall", требоваться: "required" },
  },
  {
    english: "The right to a speedy and public trial",
    russian: "Право на скорый и публичный суд",
    source: "—US Bill of Rights",
    wordTranslations: { Право: "right", на: "to", скорый: "speedy", и: "and", публичный: "public", суд: "trial" },
  },

  // US Declaration of Independence (5)
  {
    english: "We hold these truths to be self-evident",
    russian: "Мы считаем эти истины самоочевидными",
    source: "—US Declaration of Independence",
    wordTranslations: { Мы: "we", считаем: "hold", эти: "these", истины: "truths", самоочевидными: "self-evident" },
  },
  {
    english: "All men are created equal",
    russian: "Все люди созданы равными",
    source: "—US Declaration of Independence",
    wordTranslations: { Все: "all", люди: "men", созданы: "created", равными: "equal" },
  },
  {
    english: "Life, liberty, and the pursuit of happiness",
    russian: "Жизнь свобода и стремление к счастью",
    source: "—US Declaration of Independence",
    wordTranslations: {
      Жизнь: "life",
      свобода: "liberty",
      и: "and",
      стремление: "pursuit",
      к: "of",
      счастью: "happiness",
    },
  },
  {
    english: "Governments derive their just powers from the consent of the governed",
    russian: "Правительства получают свои справедливые полномочия с согласия управляемых",
    source: "—US Declaration of Independence",
    wordTranslations: {
      Правительства: "governments",
      получают: "derive",
      свои: "their",
      справедливые: "just",
      полномочия: "powers",
      с: "from",
      согласия: "consent",
      управляемых: "governed",
    },
  },
  {
    english: "When government becomes destructive, it is the right of the people to alter or abolish it",
    russian: "Когда правительство становится разрушительным это право народа изменить или упразднить его",
    source: "—US Declaration of Independence",
    wordTranslations: {
      Когда: "when",
      правительство: "government",
      становится: "becomes",
      разрушительным: "destructive",
      это: "it is",
      право: "right",
      народа: "people",
      изменить: "alter",
      или: "or",
      упразднить: "abolish",
      его: "it",
    },
  },

  // Mao's Little Red Book (10)
  {
    english: "Political power grows out of the barrel of a gun",
    russian: "Политическая власть растёт из дула ружья",
    source: "—Mao Zedong",
    wordTranslations: {
      Политическая: "political",
      власть: "power",
      растёт: "grows",
      из: "out of",
      дула: "barrel",
      ружья: "gun",
    },
  },
  {
    english: "A revolution is not a dinner party",
    russian: "Революция это не званый обед",
    source: "—Mao Zedong",
    wordTranslations: { Революция: "revolution", это: "is", не: "not", званый: "dinner", обед: "party" },
  },
  {
    english: "Let a hundred flowers bloom",
    russian: "Пусть расцветают сто цветов",
    source: "—Mao Zedong",
    wordTranslations: { Пусть: "let", расцветают: "bloom", сто: "hundred", цветов: "flowers" },
  },
  {
    english: "The people, and the people alone, are the motive force in the making of world history",
    russian: "Народ и только народ является движущей силой в создании мировой истории",
    source: "—Mao Zedong",
    wordTranslations: {
      Народ: "people",
      и: "and",
      только: "alone",
      народ: "people",
      является: "is",
      движущей: "motive",
      силой: "force",
      в: "in",
      создании: "making",
      мировой: "world",
      истории: "history",
    },
  },
  {
    english: "To read too many books is harmful",
    russian: "Читать слишком много книг вредно",
    source: "—Mao Zedong",
    wordTranslations: { Читать: "read", слишком: "too", много: "many", книг: "books", вредно: "harmful" },
  },
  {
    english: "All reactionaries are paper tigers",
    russian: "Все реакционеры это бумажные тигры",
    source: "—Mao Zedong",
    wordTranslations: { Все: "all", реакционеры: "reactionaries", это: "are", бумажные: "paper", тигры: "tigers" },
  },
  {
    english: "Women hold up half the sky",
    russian: "Женщины держат половину неба",
    source: "—Mao Zedong",
    wordTranslations: { Женщины: "women", держат: "hold up", половину: "half", неба: "sky" },
  },
  {
    english: "Wherever there is struggle there is sacrifice",
    russian: "Где есть борьба там есть жертва",
    source: "—Mao Zedong",
    wordTranslations: {
      Где: "wherever",
      есть: "there is",
      борьба: "struggle",
      там: "there",
      есть: "is",
      жертва: "sacrifice",
    },
  },
  {
    english: "We must learn to do economic work from all who know how",
    russian: "Мы должны учиться делать экономическую работу у всех кто умеет",
    source: "—Mao Zedong",
    wordTranslations: {
      Мы: "we",
      должны: "must",
      учиться: "learn",
      делать: "do",
      экономическую: "economic",
      работу: "work",
      у: "from",
      всех: "all",
      кто: "who",
      умеет: "know how",
    },
  },
  {
    english: "Practice is the sole criterion of truth",
    russian: "Практика единственный критерий истины",
    source: "—Mao Zedong",
    wordTranslations: { Практика: "practice", единственный: "sole", критерий: "criterion", истины: "truth" },
  },

  // Confucius (10)
  {
    english: "It does not matter how slowly you go as long as you do not stop",
    russian: "Не важно как медленно ты идёшь пока ты не остановишься",
    source: "—Confucius",
    wordTranslations: {
      Не: "not",
      важно: "matter",
      как: "how",
      медленно: "slowly",
      ты: "you",
      идёшь: "go",
      пока: "long as",
      ты: "you",
      не: "not",
      остановишься: "stop",
    },
  },
  {
    english: "Choose a job you love and you will never have to work a day in your life",
    russian: "Выбери работу которую любишь и тебе никогда не придётся работать ни дня в жизни",
    source: "—Confucius",
    wordTranslations: {
      Выбери: "choose",
      работу: "job",
      которую: "you",
      любишь: "love",
      и: "and",
      тебе: "you",
      никогда: "never",
      не: "not",
      придётся: "have to",
      работать: "work",
      ни: "a",
      дня: "day",
      в: "in",
      жизни: "life",
    },
  },
  {
    english: "He who knows all the answers has not been asked all the questions",
    russian: "Тот кто знает все ответы не получил всех вопросов",
    source: "—Confucius",
    wordTranslations: {
      Тот: "he",
      кто: "who",
      знает: "knows",
      все: "all",
      ответы: "answers",
      не: "not",
      получил: "been asked",
      всех: "all",
      вопросов: "questions",
    },
  },
  {
    english: "The man who moves a mountain begins by carrying away small stones",
    russian: "Человек который двигает гору начинает с переноса маленьких камней",
    source: "—Confucius",
    wordTranslations: {
      Человек: "man",
      который: "who",
      двигает: "moves",
      гору: "mountain",
      начинает: "begins",
      с: "by",
      переноса: "carrying away",
      маленьких: "small",
      камней: "stones",
    },
  },
  {
    english: "Our greatest glory is not in never falling, but in rising every time we fall",
    russian: "Наша величайшая слава не в том чтобы никогда не падать а в том чтобы подниматься каждый раз когда падаем",
    source: "—Confucius",
    wordTranslations: {
      Наша: "our",
      величайшая: "greatest",
      слава: "glory",
      не: "not",
      в: "in",
      том: "that",
      чтобы: "to",
      никогда: "never",
      не: "not",
      падать: "falling",
      а: "but",
      в: "in",
      том: "that",
      чтобы: "to",
      подниматься: "rising",
      каждый: "every",
      раз: "time",
      когда: "we",
      падаем: "fall",
    },
  },
  {
    english: "Before you embark on a journey of revenge, dig two graves",
    russian: "Прежде чем отправиться в путешествие мести выкопай две могилы",
    source: "—Confucius",
    wordTranslations: {
      Прежде: "before",
      чем: "you",
      отправиться: "embark",
      в: "on",
      путешествие: "journey",
      мести: "revenge",
      выкопай: "dig",
      две: "two",
      могилы: "graves",
    },
  },
  {
    english: "Silence is a true friend who never betrays",
    russian: "Молчание это истинный друг который никогда не предаёт",
    source: "—Confucius",
    wordTranslations: {
      Молчание: "silence",
      это: "is",
      истинный: "true",
      друг: "friend",
      который: "who",
      никогда: "never",
      не: "not",
      предаёт: "betrays",
    },
  },
  {
    english: "Real knowledge is to know the extent of one's ignorance",
    russian: "Настоящее знание это знать степень своего невежества",
    source: "—Confucius",
    wordTranslations: {
      Настоящее: "real",
      знание: "knowledge",
      это: "is",
      знать: "know",
      степень: "extent",
      своего: "one's",
      невежества: "ignorance",
    },
  },
  {
    english: "When anger rises, think of the consequences",
    russian: "Когда гнев поднимается подумай о последствиях",
    source: "—Confucius",
    wordTranslations: {
      Когда: "when",
      гнев: "anger",
      поднимается: "rises",
      подумай: "think",
      о: "of",
      последствиях: "consequences",
    },
  },
  {
    english: "Study the past if you would define the future",
    russian: "Изучай прошлое если хочешь определить будущее",
    source: "—Confucius",
    wordTranslations: {
      Изучай: "study",
      прошлое: "past",
      если: "if",
      хочешь: "you would",
      определить: "define",
      будущее: "future",
    },
  },

  // Bhagavad Gita (10)
  {
    english: "You have the right to work, but never to the fruit of work",
    russian: "У тебя есть право трудиться но никогда на плоды труда",
    source: "—Bhagavad Gita",
    wordTranslations: {
      У: "you",
      тебя: "you",
      есть: "have",
      право: "right",
      трудиться: "work",
      но: "but",
      никогда: "never",
      на: "to",
      плоды: "fruit",
      труда: "work",
    },
  },
  {
    english: "Change is the law of the universe",
    russian: "Перемена это закон вселенной",
    source: "—Bhagavad Gita",
    wordTranslations: { Перемена: "change", это: "is", закон: "law", вселенной: "universe" },
  },
  {
    english: "The soul is neither born nor does it die",
    russian: "Душа не рождается и не умирает",
    source: "—Bhagavad Gita",
    wordTranslations: { Душа: "soul", не: "neither", рождается: "born", и: "nor", не: "not", умирает: "die" },
  },
  {
    english: "A man's own self is his friend, a man's own self is his foe",
    russian: "Собственное я человека его друг собственное я человека его враг",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Собственное: "own",
      я: "self",
      человека: "man's",
      его: "his",
      друг: "friend",
      собственное: "own",
      я: "self",
      человека: "man's",
      его: "his",
      враг: "foe",
    },
  },
  {
    english: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place",
    russian: "Когда медитация освоена ум непоколебим как пламя лампы в безветренном месте",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Когда: "when",
      медитация: "meditation",
      освоена: "mastered",
      ум: "mind",
      непоколебим: "unwavering",
      как: "like",
      пламя: "flame",
      лампы: "lamp",
      в: "in",
      безветренном: "windless",
      месте: "place",
    },
  },
  {
    english: "Set thy heart upon thy work but never on its reward",
    russian: "Направь своё сердце на свою работу но никогда на её награду",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Направь: "set",
      своё: "thy",
      сердце: "heart",
      на: "upon",
      свою: "thy",
      работу: "work",
      но: "but",
      никогда: "never",
      на: "on",
      её: "its",
      награду: "reward",
    },
  },
  {
    english: "The mind is restless and difficult to restrain",
    russian: "Ум беспокоен и труден для укрощения",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Ум: "mind",
      беспокоен: "restless",
      и: "and",
      труден: "difficult",
      для: "to",
      укрощения: "restrain",
    },
  },
  {
    english: "One who sees inaction in action and action in inaction is intelligent among men",
    russian: "Тот кто видит бездействие в действии и действие в бездействии разумен среди людей",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Тот: "one",
      кто: "who",
      видит: "sees",
      бездействие: "inaction",
      в: "in",
      действии: "action",
      и: "and",
      действие: "action",
      в: "in",
      бездействии: "inaction",
      разумен: "intelligent",
      среди: "among",
      людей: "men",
    },
  },
  {
    english: "Whatever happened was good, what's happening is going well, whatever will happen will also be good",
    russian: "Что бы ни случилось было хорошо что происходит идёт хорошо что бы ни случилось будет тоже хорошо",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Что: "whatever",
      бы: "ever",
      ни: "not",
      случилось: "happened",
      было: "was",
      хорошо: "good",
      что: "what's",
      происходит: "happening",
      идёт: "is going",
      хорошо: "well",
      что: "whatever",
      бы: "will",
      ни: "not",
      случилось: "happen",
      будет: "will",
      тоже: "also",
      хорошо: "good",
    },
  },
  {
    english: "There is neither this world nor the world beyond nor happiness for the one who doubts",
    russian: "Нет ни этого мира ни мира за пределами ни счастья для того кто сомневается",
    source: "—Bhagavad Gita",
    wordTranslations: {
      Нет: "neither",
      ни: "nor",
      этого: "this",
      мира: "world",
      ни: "nor",
      мира: "world",
      за: "beyond",
      пределами: "beyond",
      ни: "nor",
      счастья: "happiness",
      для: "for",
      того: "one",
      кто: "who",
      сомневается: "doubts",
    },
  },

  // Karl Marx (10)
  {
    english: "Workers of the world, unite!",
    russian: "Пролетарии всех стран соединяйтесь!",
    source: "—Karl Marx",
    wordTranslations: { Пролетарии: "workers", всех: "world", стран: "world", соединяйтесь: "unite" },
  },
  {
    english: "From each according to his ability, to each according to his needs",
    russian: "От каждого по способностям каждому по потребностям",
    source: "—Karl Marx",
    wordTranslations: {
      От: "from",
      каждого: "each",
      по: "according to",
      способностям: "ability",
      каждому: "each",
      по: "according to",
      потребностям: "needs",
    },
  },
  {
    english: "Religion is the opium of the people",
    russian: "Религия это опиум народа",
    source: "—Karl Marx",
    wordTranslations: { Религия: "religion", это: "is", опиум: "opium", народа: "people" },
  },
  {
    english: "The philosophers have only interpreted the world, the point is to change it",
    russian: "Философы лишь интерпретировали мир суть в том чтобы изменить его",
    source: "—Karl Marx",
    wordTranslations: {
      Философы: "philosophers",
      лишь: "only",
      интерпретировали: "interpreted",
      мир: "world",
      суть: "point",
      в: "is",
      том: "to",
      чтобы: "to",
      изменить: "change",
      его: "it",
    },
  },
  {
    english: "History repeats itself, first as tragedy, second as farce",
    russian: "История повторяется сначала как трагедия затем как фарс",
    source: "—Karl Marx",
    wordTranslations: {
      История: "history",
      повторяется: "repeats",
      сначала: "first",
      как: "as",
      трагедия: "tragedy",
      затем: "second",
      как: "as",
      фарс: "farce",
    },
  },
  {
    english: "The production of too many useful things results in too many useless people",
    russian: "Производство слишком многих полезных вещей приводит к слишком многим бесполезным людям",
    source: "—Karl Marx",
    wordTranslations: {
      Производство: "production",
      слишком: "too",
      многих: "many",
      полезных: "useful",
      вещей: "things",
      приводит: "results",
      к: "in",
      слишком: "too",
      многим: "many",
      бесполезным: "useless",
      людям: "people",
    },
  },
  {
    english: "The ruling ideas are nothing more than the ideal expression of the dominant material relationships",
    russian: "Господствующие идеи не что иное как идеальное выражение господствующих материальных отношений",
    source: "—Karl Marx",
    wordTranslations: {
      Господствующие: "ruling",
      идеи: "ideas",
      не: "nothing",
      что: "more",
      иное: "than",
      как: "as",
      идеальное: "ideal",
      выражение: "expression",
      господствующих: "dominant",
      материальных: "material",
      отношений: "relationships",
    },
  },
  {
    english: "Capital is dead labor which vampire-like lives only by sucking living labor",
    russian: "Капитал это мёртвый труд который как вампир живёт только высасывая живой труд",
    source: "—Karl Marx",
    wordTranslations: {
      Капитал: "capital",
      это: "is",
      мёртвый: "dead",
      труд: "labor",
      который: "which",
      как: "like",
      вампир: "vampire",
      живёт: "lives",
      только: "only",
      высасывая: "sucking",
      живой: "living",
      труд: "labor",
    },
  },
  {
    english: "Social progress can be measured by the social position of the female sex",
    russian: "Социальный прогресс можно измерить социальным положением женского пола",
    source: "—Karl Marx",
    wordTranslations: {
      Социальный: "social",
      прогресс: "progress",
      можно: "can",
      измерить: "measured",
      социальным: "social",
      положением: "position",
      женского: "female",
      пола: "sex",
    },
  },
  {
    english: "The only antidote to mental suffering is physical pain",
    russian: "Единственное противоядие от душевных страданий это физическая боль",
    source: "—Karl Marx",
    wordTranslations: {
      Единственное: "only",
      противоядие: "antidote",
      от: "to",
      душевных: "mental",
      страданий: "suffering",
      это: "is",
      физическая: "physical",
      боль: "pain",
    },
  },

  // Vladimir Lenin (10)
  {
    english: "There are no morals in politics, only expedience",
    russian: "В политике нет морали есть только целесообразность",
    source: "—Vladimir Lenin",
    wordTranslations: {
      В: "in",
      политике: "politics",
      нет: "no",
      морали: "morals",
      есть: "there are",
      только: "only",
      целесообразность: "expedience",
    },
  },
  {
    english: "A lie told often enough becomes the truth",
    russian: "Ложь сказанная достаточно часто становится правдой",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Ложь: "lie",
      сказанная: "told",
      достаточно: "enough",
      часто: "often",
      становится: "becomes",
      правдой: "truth",
    },
  },
  {
    english:
      "Freedom in capitalist society always remains about the same as it was in ancient Greek republics: freedom for slave owners",
    russian:
      "Свобода в капиталистическом обществе всегда остаётся примерно такой же как в древнегреческих республиках: свобода для рабовладельцев",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Свобода: "freedom",
      в: "in",
      капиталистическом: "capitalist",
      обществе: "society",
      всегда: "always",
      остаётся: "remains",
      примерно: "about",
      такой: "same",
      же: "as",
      как: "as",
      в: "in",
      древнегреческих: "Greek",
      республиках: "republics",
      свобода: "freedom",
      для: "for",
      рабовладельцев: "slave owners",
    },
  },
  {
    english: "One man with a gun can control a hundred without one",
    russian: "Один человек с ружьём может контролировать сотню без него",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Один: "one",
      человек: "man",
      с: "with",
      ружьём: "gun",
      может: "can",
      контролировать: "control",
      сотню: "hundred",
      без: "without",
      него: "one",
    },
  },
  {
    english: "Trust is good, control is better",
    russian: "Доверяй но проверяй",
    source: "—Vladimir Lenin",
    wordTranslations: { Доверяй: "trust", но: "but", проверяй: "verify" },
  },
  {
    english: "It is true that liberty is precious, so precious that it must be carefully rationed",
    russian: "Свобода действительно драгоценна настолько драгоценна что её нужно тщательно нормировать",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Свобода: "liberty",
      действительно: "truly",
      драгоценна: "precious",
      настолько: "so",
      драгоценна: "precious",
      что: "that",
      её: "it",
      нужно: "must",
      тщательно: "carefully",
      нормировать: "rationed",
    },
  },
  {
    english: "Give me four years to teach the children and the seed I have sown will never be uprooted",
    russian: "Дайте мне четыре года чтобы учить детей и семя которое я посеял никогда не будет вырвано",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Дайте: "give",
      мне: "me",
      четыре: "four",
      года: "years",
      чтобы: "to",
      учить: "teach",
      детей: "children",
      и: "and",
      семя: "seed",
      которое: "which",
      я: "I",
      посеял: "sown",
      никогда: "never",
      не: "not",
      будет: "will be",
      вырвано: "uprooted",
    },
  },
  {
    english: "The best way to destroy the capitalist system is to debauch the currency",
    russian: "Лучший способ разрушить капиталистическую систему это развратить валюту",
    source: "—Vladimir Lenin",
    wordTranslations: {
      Лучший: "best",
      способ: "way",
      разрушить: "destroy",
      капиталистическую: "capitalist",
      систему: "system",
      это: "is",
      развратить: "debauch",
      валюту: "currency",
    },
  },
  {
    english: "Sometimes history needs a push",
    russian: "Иногда истории нужен толчок",
    source: "—Vladimir Lenin",
    wordTranslations: { Иногда: "sometimes", истории: "history", нужен: "needs", толчок: "push" },
  },
  {
    english: "The goal of socialism is communism",
    russian: "Цель социализма это коммунизм",
    source: "—Vladimir Lenin",
    wordTranslations: { Цель: "goal", социализма: "socialism", это: "is", коммунизм: "communism" },
  },

  // Albert Einstein (5)
  {
    english: "Imagination is more important than knowledge",
    russian: "Воображение важнее знания",
    source: "—Albert Einstein",
    wordTranslations: { Воображение: "imagination", важнее: "more important", знания: "knowledge" },
  },
  {
    english: "The important thing is not to stop questioning",
    russian: "Важно не переставать задавать вопросы",
    source: "—Albert Einstein",
    wordTranslations: { Важно: "important", не: "not", переставать: "stop", задавать: "asking", вопросы: "questions" },
  },
  {
    english: "Logic will get you from A to B, imagination will take you everywhere",
    russian: "Логика доведёт тебя от А до Б воображение приведёт тебя повсюду",
    source: "—Albert Einstein",
    wordTranslations: {
      Логика: "logic",
      доведёт: "get",
      тебя: "you",
      от: "from",
      А: "A",
      до: "to",
      Б: "B",
      воображение: "imagination",
      приведёт: "take",
      тебя: "you",
      повсюду: "everywhere",
    },
  },
  {
    english: "Life is like riding a bicycle, to keep your balance you must keep moving",
    russian: "Жизнь как езда на велосипеде чтобы сохранять равновесие ты должен продолжать двигаться",
    source: "—Albert Einstein",
    wordTranslations: {
      Жизнь: "life",
      как: "like",
      езда: "riding",
      на: "on",
      велосипеде: "bicycle",
      чтобы: "to",
      сохранять: "keep",
      равновесие: "balance",
      ты: "you",
      должен: "must",
      продолжать: "keep",
      двигаться: "moving",
    },
  },
  {
    english: "The only source of knowledge is experience",
    russian: "Единственный источник знания это опыт",
    source: "—Albert Einstein",
    wordTranslations: { Единственный: "only", источник: "source", знания: "knowledge", это: "is", опыт: "experience" },
  },

  // Humorous observations (20)
  {
    english: "I have not failed, I've just found ten thousand ways that won't work",
    russian: "Я не потерпел неудачу я просто нашёл десять тысяч способов которые не работают",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Я: "I",
      не: "not",
      потерпел: "failed",
      неудачу: "failed",
      я: "I",
      просто: "just",
      нашёл: "found",
      десять: "ten",
      тысяч: "thousand",
      способов: "ways",
      которые: "that",
      не: "not",
      работают: "work",
    },
  },
  {
    english: "Common sense is not so common",
    russian: "Здравый смысл не так уж распространён",
    source: "—Humorous Wisdom",
    wordTranslations: { Здравый: "common", смысл: "sense", не: "not", так: "so", уж: "so", распространён: "common" },
  },
  {
    english: "The early bird gets the worm, but the second mouse gets the cheese",
    russian: "Ранняя птица получает червя но вторая мышь получает сыр",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Ранняя: "early",
      птица: "bird",
      получает: "gets",
      червя: "worm",
      но: "but",
      вторая: "second",
      мышь: "mouse",
      получает: "gets",
      сыр: "cheese",
    },
  },
  {
    english: "I can resist everything except temptation",
    russian: "Я могу противостоять всему кроме соблазна",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Я: "I",
      могу: "can",
      противостоять: "resist",
      всему: "everything",
      кроме: "except",
      соблазна: "temptation",
    },
  },
  {
    english: "If you think nobody cares if you're alive, try missing a couple of payments",
    russian: "Если думаешь что никому нет дела жив ты или нет попробуй пропустить пару платежей",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Если: "if",
      думаешь: "think",
      что: "that",
      никому: "nobody",
      нет: "not",
      дела: "cares",
      жив: "alive",
      ты: "you",
      или: "or",
      нет: "not",
      попробуй: "try",
      пропустить: "missing",
      пару: "couple",
      платежей: "payments",
    },
  },
  {
    english: "The difference between genius and stupidity is that genius has its limits",
    russian: "Разница между гением и глупостью в том что у гения есть пределы",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Разница: "difference",
      между: "between",
      гением: "genius",
      и: "and",
      глупостью: "stupidity",
      в: "is",
      том: "that",
      что: "that",
      у: "has",
      гения: "genius",
      есть: "has",
      пределы: "limits",
    },
  },
  {
    english: "I'm not superstitious, but I am a little stitious",
    russian: "Я не суеверен но немного верен",
    source: "—Humorous Wisdom",
    wordTranslations: { Я: "I", не: "not", суеверен: "superstitious", но: "but", немного: "little", верен: "stitious" },
  },
  {
    english: "Knowledge is knowing that a tomato is a fruit, wisdom is not putting it in a fruit salad",
    russian: "Знание это знать что помидор это фрукт мудрость это не класть его во фруктовый салат",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Знание: "knowledge",
      это: "is",
      знать: "knowing",
      что: "that",
      помидор: "tomato",
      это: "is",
      фрукт: "fruit",
      мудрость: "wisdom",
      это: "is",
      не: "not",
      класть: "putting",
      его: "it",
      во: "in",
      фруктовый: "fruit",
      салат: "salad",
    },
  },
  {
    english: "Behind every successful man is a woman rolling her eyes",
    russian: "За каждым успешным мужчиной стоит женщина закатывающая глаза",
    source: "—Humorous Wisdom",
    wordTranslations: {
      За: "behind",
      каждым: "every",
      успешным: "successful",
      мужчиной: "man",
      стоит: "is",
      женщина: "woman",
      закатывающая: "rolling",
      глаза: "eyes",
    },
  },
  {
    english: "I always arrive late at the office, but I make up for it by leaving early",
    russian: "Я всегда прихожу на работу поздно но компенсирую это тем что ухожу рано",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Я: "I",
      всегда: "always",
      прихожу: "arrive",
      на: "at",
      работу: "office",
      поздно: "late",
      но: "but",
      компенсирую: "make up",
      это: "for it",
      тем: "by",
      что: "that",
      ухожу: "leaving",
      рано: "early",
    },
  },
  {
    english: "I'm not arguing, I'm just explaining why I'm right",
    russian: "Я не спорю я просто объясняю почему я прав",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Я: "I",
      не: "not",
      спорю: "arguing",
      я: "I",
      просто: "just",
      объясняю: "explaining",
      почему: "why",
      я: "I",
      прав: "right",
    },
  },
  {
    english: "I'm on a whiskey diet, I've lost three days already",
    russian: "Я на виски диете я уже потерял три дня",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Я: "I",
      на: "on",
      виски: "whiskey",
      диете: "diet",
      я: "I",
      уже: "already",
      потерял: "lost",
      три: "three",
      дня: "days",
    },
  },
  {
    english: "The road to success is always under construction",
    russian: "Дорога к успеху всегда в стадии строительства",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Дорога: "road",
      к: "to",
      успеху: "success",
      всегда: "always",
      в: "under",
      стадии: "under",
      строительства: "construction",
    },
  },
  {
    english: "If at first you don't succeed, then skydiving definitely isn't for you",
    russian: "Если сначала у тебя не получилось то парашютный спорт определённо не для тебя",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Если: "if",
      сначала: "first",
      у: "you",
      тебя: "you",
      не: "not",
      получилось: "succeed",
      то: "then",
      парашютный: "skydiving",
      спорт: "skydiving",
      определённо: "definitely",
      не: "not",
      для: "for",
      тебя: "you",
    },
  },
  {
    english: "I used to think I was indecisive, but now I'm not too sure",
    russian: "Раньше я думал что я нерешителен но теперь я не слишком уверен",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Раньше: "used to",
      я: "I",
      думал: "think",
      что: "that",
      я: "I",
      нерешителен: "indecisive",
      но: "but",
      теперь: "now",
      я: "I",
      не: "not",
      слишком: "too",
      уверен: "sure",
    },
  },
  {
    english: "The best time to plant a tree was twenty years ago, the second best time is now",
    russian: "Лучшее время посадить дерево было двадцать лет назад второе лучшее время это сейчас",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Лучшее: "best",
      время: "time",
      посадить: "plant",
      дерево: "tree",
      было: "was",
      двадцать: "twenty",
      лет: "years",
      назад: "ago",
      второе: "second",
      лучшее: "best",
      время: "time",
      это: "is",
      сейчас: "now",
    },
  },
  {
    english: "A day without sunshine is like, you know, night",
    russian: "День без солнечного света это как ну знаешь ночь",
    source: "—Humorous Wisdom",
    wordTranslations: {
      День: "day",
      без: "without",
      солнечного: "sunshine",
      света: "sunshine",
      это: "is",
      как: "like",
      ну: "you",
      знаешь: "know",
      ночь: "night",
    },
  },
  {
    english: "Change is inevitable, except from a vending machine",
    russian: "Перемены неизбежны кроме как из торгового автомата",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Перемены: "change",
      неизбежны: "inevitable",
      кроме: "except",
      как: "from",
      из: "from",
      торгового: "vending",
      автомата: "machine",
    },
  },
  {
    english: "Light travels faster than sound, that's why some people appear bright until you hear them speak",
    russian: "Свет движется быстрее звука поэтому некоторые люди кажутся яркими пока ты не услышишь как они говорят",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Свет: "light",
      движется: "travels",
      быстрее: "faster",
      звука: "sound",
      поэтому: "that's why",
      некоторые: "some",
      люди: "people",
      кажутся: "appear",
      яркими: "bright",
      пока: "until",
      ты: "you",
      не: "not",
      услышишь: "hear",
      как: "how",
      они: "them",
      говорят: "speak",
    },
  },
  {
    english: "War does not determine who is right, only who is left",
    russian: "Война не определяет кто прав только кто остался",
    source: "—Humorous Wisdom",
    wordTranslations: {
      Война: "war",
      не: "not",
      определяет: "determine",
      кто: "who",
      прав: "right",
      только: "only",
      кто: "who",
      остался: "left",
    },
  },

  // Shakespeare (10)
  {
    english: "To be or not to be, that is the question",
    russian: "Быть или не быть вот в чём вопрос",
    source: "—Shakespeare",
    wordTranslations: {
      Быть: "be",
      или: "or",
      не: "not",
      быть: "be",
      вот: "that",
      в: "is",
      чём: "the",
      вопрос: "question",
    },
  },
  {
    english: "All the world's a stage and all the men and women merely players",
    russian: "Весь мир театр и все мужчины и женщины просто актёры",
    source: "—Shakespeare",
    wordTranslations: {
      Весь: "all",
      мир: "world",
      театр: "stage",
      и: "and",
      все: "all",
      мужчины: "men",
      и: "and",
      женщины: "women",
      просто: "merely",
      актёры: "players",
    },
  },
  {
    english: "Some are born great, some achieve greatness, and some have greatness thrust upon them",
    russian: "Кто-то рождается великим кто-то достигает величия а кому-то величие навязывается",
    source: "—Shakespeare",
    wordTranslations: {
      "Кто-то": "some",
      рождается: "born",
      великим: "great",
      "кто-то": "some",
      достигает: "achieve",
      величия: "greatness",
      а: "and",
      "кому-то": "some",
      величие: "greatness",
      навязывается: "thrust upon",
    },
  },
  {
    english: "The course of true love never did run smooth",
    russian: "Путь истинной любви никогда не был гладким",
    source: "—Shakespeare",
    wordTranslations: {
      Путь: "course",
      истинной: "true",
      любви: "love",
      никогда: "never",
      не: "not",
      был: "did",
      гладким: "smooth",
    },
  },
  {
    english: "Brevity is the soul of wit",
    russian: "Краткость душа остроумия",
    source: "—Shakespeare",
    wordTranslations: { Краткость: "brevity", душа: "soul", остроумия: "wit" },
  },
  {
    english: "What's in a name? That which we call a rose by any other name would smell as sweet",
    russian: "Что в имени? То что мы называем розой под любым другим именем пахло бы так же сладко",
    source: "—Shakespeare",
    wordTranslations: {
      Что: "what",
      в: "in",
      имени: "name",
      То: "that",
      что: "which",
      мы: "we",
      называем: "call",
      розой: "rose",
      под: "by",
      любым: "any",
      другим: "other",
      именем: "name",
      пахло: "smell",
      бы: "would",
      так: "as",
      же: "as",
      сладко: "sweet",
    },
  },
  {
    english: "Love all, trust a few, do wrong to none",
    russian: "Люби всех доверяй немногим не делай зла никому",
    source: "—Shakespeare",
    wordTranslations: {
      Люби: "love",
      всех: "all",
      доверяй: "trust",
      немногим: "few",
      не: "not",
      делай: "do",
      зла: "wrong",
      никому: "none",
    },
  },
  {
    english: "The fool doth think he is wise, but the wise man knows himself to be a fool",
    russian: "Дурак думает что он мудр но мудрец знает что он дурак",
    source: "—Shakespeare",
    wordTranslations: {
      Дурак: "fool",
      думает: "think",
      что: "that",
      он: "he",
      мудр: "wise",
      но: "but",
      мудрец: "wise man",
      знает: "knows",
      что: "that",
      он: "he",
      дурак: "fool",
    },
  },
  {
    english: "Cowards die many times before their deaths",
    russian: "Трусы умирают много раз до своей смерти",
    source: "—Shakespeare",
    wordTranslations: {
      Трусы: "cowards",
      умирают: "die",
      много: "many",
      раз: "times",
      до: "before",
      своей: "their",
      смерти: "deaths",
    },
  },
  {
    english: "We know what we are, but know not what we may be",
    russian: "Мы знаем кто мы есть но не знаем кем мы можем быть",
    source: "—Shakespeare",
    wordTranslations: {
      Мы: "we",
      знаем: "know",
      кто: "what",
      мы: "we",
      есть: "are",
      но: "but",
      не: "not",
      знаем: "know",
      кем: "what",
      мы: "we",
      можем: "may",
      быть: "be",
    },
  },

  // Mark Twain (10)
  {
    english: "The secret of getting ahead is getting started",
    russian: "Секрет продвижения вперёд это начать",
    source: "—Mark Twain",
    wordTranslations: {
      Секрет: "secret",
      продвижения: "getting",
      вперёд: "ahead",
      это: "is",
      начать: "getting started",
    },
  },
  {
    english: "Kindness is the language which the deaf can hear and the blind can see",
    russian: "Доброта это язык который глухие могут услышать а слепые увидеть",
    source: "—Mark Twain",
    wordTranslations: {
      Доброта: "kindness",
      это: "is",
      язык: "language",
      который: "which",
      глухие: "deaf",
      могут: "can",
      услышать: "hear",
      а: "and",
      слепые: "blind",
      увидеть: "see",
    },
  },
  {
    english: "Never put off till tomorrow what may be done day after tomorrow just as well",
    russian: "Никогда не откладывай на завтра то что можно сделать послезавтра так же хорошо",
    source: "—Mark Twain",
    wordTranslations: {
      Никогда: "never",
      не: "not",
      откладывай: "put off",
      на: "till",
      завтра: "tomorrow",
      то: "what",
      что: "what",
      можно: "may",
      сделать: "done",
      послезавтра: "day after tomorrow",
      так: "just",
      же: "as",
      хорошо: "well",
    },
  },
  {
    english: "If you tell the truth, you don't have to remember anything",
    russian: "Если говоришь правду тебе не нужно ничего помнить",
    source: "—Mark Twain",
    wordTranslations: {
      Если: "if",
      говоришь: "tell",
      правду: "truth",
      тебе: "you",
      не: "not",
      нужно: "have to",
      ничего: "anything",
      помнить: "remember",
    },
  },
  {
    english: "The man who does not read has no advantage over the man who cannot read",
    russian: "Человек который не читает не имеет преимущества перед человеком который не умеет читать",
    source: "—Mark Twain",
    wordTranslations: {
      Человек: "man",
      который: "who",
      не: "not",
      читает: "read",
      не: "no",
      имеет: "has",
      преимущества: "advantage",
      перед: "over",
      человеком: "man",
      который: "who",
      не: "cannot",
      умеет: "can",
      читать: "read",
    },
  },
  {
    english: "It's not the size of the dog in the fight, it's the size of the fight in the dog",
    russian: "Важен не размер собаки в драке а размер драки в собаке",
    source: "—Mark Twain",
    wordTranslations: {
      Важен: "it's",
      не: "not",
      размер: "size",
      собаки: "dog",
      в: "in",
      драке: "fight",
      а: "it's",
      размер: "size",
      драки: "fight",
      в: "in",
      собаке: "dog",
    },
  },
  {
    english: "Good friends, good books, and a sleepy conscience: this is the ideal life",
    russian: "Хорошие друзья хорошие книги и спокойная совесть это идеальная жизнь",
    source: "—Mark Twain",
    wordTranslations: {
      Хорошие: "good",
      друзья: "friends",
      хорошие: "good",
      книги: "books",
      и: "and",
      спокойная: "sleepy",
      совесть: "conscience",
      это: "this is",
      идеальная: "ideal",
      жизнь: "life",
    },
  },
  {
    english: "I have never let my schooling interfere with my education",
    russian: "Я никогда не позволял своей учёбе мешать моему образованию",
    source: "—Mark Twain",
    wordTranslations: {
      Я: "I",
      никогда: "never",
      не: "not",
      позволял: "let",
      своей: "my",
      учёбе: "schooling",
      мешать: "interfere",
      моему: "my",
      образованию: "education",
    },
  },
  {
    english: "When angry, count to four, when very angry, swear",
    russian: "Когда зол считай до четырёх когда очень зол ругайся",
    source: "—Mark Twain",
    wordTranslations: {
      Когда: "when",
      зол: "angry",
      считай: "count",
      до: "to",
      четырёх: "four",
      когда: "when",
      очень: "very",
      зол: "angry",
      ругайся: "swear",
    },
  },
  {
    english: "Age is an issue of mind over matter, if you don't mind, it doesn't matter",
    russian: "Возраст это вопрос разума над материей если тебя это не волнует это не имеет значения",
    source: "—Mark Twain",
    wordTranslations: {
      Возраст: "age",
      это: "is",
      вопрос: "issue",
      разума: "mind",
      над: "over",
      материей: "matter",
      если: "if",
      тебя: "you",
      это: "it",
      не: "not",
      волнует: "mind",
      это: "it",
      не: "not",
      имеет: "does",
      значения: "matter",
    },
  },

  // Winston Churchill (5)
  {
    english: "Success is not final, failure is not fatal: it is the courage to continue that counts",
    russian: "Успех не окончателен неудача не фатальна важна смелость продолжать",
    source: "—Winston Churchill",
    wordTranslations: {
      Успех: "success",
      не: "not",
      окончателен: "final",
      неудача: "failure",
      не: "not",
      фатальна: "fatal",
      важна: "it is",
      смелость: "courage",
      продолжать: "continue",
      что: "that",
      считается: "counts",
    },
  },
  {
    english: "We make a living by what we get, but we make a life by what we give",
    russian: "Мы зарабатываем на жизнь тем что получаем но создаём жизнь тем что даём",
    source: "—Winston Churchill",
    wordTranslations: {
      Мы: "we",
      зарабатываем: "make",
      на: "a",
      жизнь: "living",
      тем: "by",
      что: "what",
      получаем: "get",
      но: "but",
      создаём: "make",
      жизнь: "life",
      тем: "by",
      что: "what",
      даём: "give",
    },
  },
  {
    english: "The pessimist sees difficulty in every opportunity, the optimist sees opportunity in every difficulty",
    russian: "Пессимист видит трудность в каждой возможности оптимист видит возможность в каждой трудности",
    source: "—Winston Churchill",
    wordTranslations: {
      Пессимист: "pessimist",
      видит: "sees",
      трудность: "difficulty",
      в: "in",
      каждой: "every",
      возможности: "opportunity",
      оптимист: "optimist",
      видит: "sees",
      возможность: "opportunity",
      в: "in",
      каждой: "every",
      трудности: "difficulty",
    },
  },
  {
    english: "Courage is what it takes to stand up and speak, courage is also what it takes to sit down and listen",
    russian: "Мужество это то что нужно чтобы встать и говорить мужество это также то что нужно чтобы сесть и слушать",
    source: "—Winston Churchill",
    wordTranslations: {
      Мужество: "courage",
      это: "is",
      то: "what",
      что: "it",
      нужно: "takes",
      чтобы: "to",
      встать: "stand up",
      и: "and",
      говорить: "speak",
      мужество: "courage",
      это: "is",
      также: "also",
      то: "what",
      что: "it",
      нужно: "takes",
      чтобы: "to",
      сесть: "sit down",
      и: "and",
      слушать: "listen",
    },
  },
  {
    english: "You have enemies? Good, that means you've stood up for something in your life",
    russian: "У тебя есть враги? Хорошо это значит ты за что-то стоял в своей жизни",
    source: "—Winston Churchill",
    wordTranslations: {
      У: "you",
      тебя: "you",
      есть: "have",
      враги: "enemies",
      Хорошо: "good",
      это: "that",
      значит: "means",
      ты: "you",
      за: "for",
      "что-то": "something",
      стоял: "stood up",
      в: "in",
      своей: "your",
      жизни: "life",
    },
  },

  // Oscar Wilde (10)
  {
    english: "Be yourself, everyone else is already taken",
    russian: "Будь собой все остальные уже заняты",
    source: "—Oscar Wilde",
    wordTranslations: {
      Будь: "be",
      собой: "yourself",
      все: "everyone",
      остальные: "else",
      уже: "already",
      заняты: "taken",
    },
  },
  {
    english: "To live is the rarest thing in the world, most people exist, that is all",
    russian: "Жить это самая редкая вещь в мире большинство людей существуют вот и всё",
    source: "—Oscar Wilde",
    wordTranslations: {
      Жить: "live",
      это: "is",
      самая: "rarest",
      редкая: "rare",
      вещь: "thing",
      в: "in",
      мире: "world",
      большинство: "most",
      людей: "people",
      существуют: "exist",
      вот: "that",
      и: "is",
      всё: "all",
    },
  },
  {
    english: "We are all in the gutter, but some of us are looking at the stars",
    russian: "Мы все в канаве но некоторые из нас смотрят на звёзды",
    source: "—Oscar Wilde",
    wordTranslations: {
      Мы: "we",
      все: "all",
      в: "in",
      канаве: "gutter",
      но: "but",
      некоторые: "some",
      из: "of",
      нас: "us",
      смотрят: "looking",
      на: "at",
      звёзды: "stars",
    },
  },
  {
    english: "There is only one thing in the world worse than being talked about, and that is not being talked about",
    russian: "Есть только одна вещь в мире хуже чем быть темой разговоров и это не быть темой разговоров",
    source: "—Oscar Wilde",
    wordTranslations: {
      Есть: "there is",
      только: "only",
      одна: "one",
      вещь: "thing",
      в: "in",
      мире: "world",
      хуже: "worse",
      чем: "than",
      быть: "being",
      темой: "talked",
      разговоров: "about",
      и: "and",
      это: "that",
      не: "not",
      быть: "being",
      темой: "talked",
      разговоров: "about",
    },
  },
  {
    english: "I can resist anything but temptation",
    russian: "Я могу противостоять всему кроме соблазна",
    source: "—Oscar Wilde",
    wordTranslations: {
      Я: "I",
      могу: "can",
      противостоять: "resist",
      всему: "anything",
      кроме: "but",
      соблазна: "temptation",
    },
  },
  {
    english: "Experience is the name everyone gives to their mistakes",
    russian: "Опыт это имя которое каждый даёт своим ошибкам",
    source: "—Oscar Wilde",
    wordTranslations: {
      Опыт: "experience",
      это: "is",
      имя: "name",
      которое: "which",
      каждый: "everyone",
      даёт: "gives",
      своим: "their",
      ошибкам: "mistakes",
    },
  },
  {
    english: "The truth is rarely pure and never simple",
    russian: "Истина редко чиста и никогда не проста",
    source: "—Oscar Wilde",
    wordTranslations: {
      Истина: "truth",
      редко: "rarely",
      чиста: "pure",
      и: "and",
      никогда: "never",
      не: "not",
      проста: "simple",
    },
  },
  {
    english: "A cynic is a man who knows the price of everything and the value of nothing",
    russian: "Циник это человек который знает цену всего и ценность ничего",
    source: "—Oscar Wilde",
    wordTranslations: {
      Циник: "cynic",
      это: "is",
      человек: "man",
      который: "who",
      знает: "knows",
      цену: "price",
      всего: "everything",
      и: "and",
      ценность: "value",
      ничего: "nothing",
    },
  },
  {
    english: "I have the simplest tastes, I am always satisfied with the best",
    russian: "У меня простейшие вкусы я всегда удовлетворён лучшим",
    source: "—Oscar Wilde",
    wordTranslations: {
      У: "I",
      меня: "have",
      простейшие: "simplest",
      вкусы: "tastes",
      я: "I",
      всегда: "always",
      удовлетворён: "satisfied",
      лучшим: "best",
    },
  },
  {
    english: "Quotation is a serviceable substitute for wit",
    russian: "Цитата это полезная замена остроумию",
    source: "—Oscar Wilde",
    wordTranslations: {
      Цитата: "quotation",
      это: "is",
      полезная: "serviceable",
      замена: "substitute",
      остроумию: "wit",
    },
  },
]
