export interface Phrase {
  english: string
  russian: string
  source: string
  translations: Record<string, string>
}

export const phrases: Phrase[] = [
  // Quran (15)
  {
    english: "Speak good words to all people",
    russian: "Говорите добрые слова всем людям",
    source: "The Quran",
    translations: { Говорите: "Speak", добрые: "good", слова: "words", всем: "to all", людям: "people" },
  },
  {
    english: "Knowledge is the treasure of wise men",
    russian: "Знание это сокровище мудрецов",
    source: "The Quran",
    translations: { Знание: "Knowledge", это: "is", сокровище: "treasure", мудрецов: "of wise men" },
  },
  {
    english: "Patience is the key to relief",
    russian: "Терпение это ключ к облегчению",
    source: "The Quran",
    translations: { Терпение: "Patience", это: "is", ключ: "key", к: "to", облегчению: "relief" },
  },
  {
    english: "The best of you are those who learn",
    russian: "Лучшие из вас те кто учится",
    source: "The Quran",
    translations: { Лучшие: "The best", из: "of", вас: "you", те: "those", кто: "who", учится: "learn" },
  },
  {
    english: "Do good and good will come to you",
    russian: "Делай добро и добро придет к тебе",
    source: "The Quran",
    translations: { Делай: "Do", добро: "good", и: "and", придет: "will come", к: "to", тебе: "you" },
  },
  {
    english: "Truth stands clear from error",
    russian: "Истина ясно отличается от заблуждения",
    source: "The Quran",
    translations: { Истина: "Truth", ясно: "clear", отличается: "stands", от: "from", заблуждения: "error" },
  },
  {
    english: "Help others and you will be helped",
    russian: "Помогай другим и тебе помогут",
    source: "The Quran",
    translations: { Помогай: "Help", другим: "others", и: "and", тебе: "you", помогут: "will be helped" },
  },
  {
    english: "Kindness is a mark of faith",
    russian: "Доброта это признак веры",
    source: "The Quran",
    translations: { Доброта: "Kindness", это: "is", признак: "mark", веры: "of faith" },
  },
  {
    english: "Seek knowledge from cradle to grave",
    russian: "Ищи знания от колыбели до могилы",
    source: "The Quran",
    translations: { Ищи: "Seek", знания: "knowledge", от: "from", колыбели: "cradle", до: "to", могилы: "grave" },
  },
  {
    english: "The strongest among you is gentle",
    russian: "Самый сильный среди вас добрый",
    source: "The Quran",
    translations: { Самый: "The most", сильный: "strong", среди: "among", вас: "you", добрый: "gentle" },
  },
  {
    english: "Give thanks for what you have",
    russian: "Благодари за то что у тебя есть",
    source: "The Quran",
    translations: { Благодари: "Give thanks", за: "for", то: "what", что: "that", у: "at", тебя: "you", есть: "have" },
  },
  {
    english: "Peace comes from within",
    russian: "Мир приходит изнутри",
    source: "The Quran",
    translations: { Мир: "Peace", приходит: "comes", изнутри: "from within" },
  },
  {
    english: "Be kind to your neighbors",
    russian: "Будь добр к своим соседям",
    source: "The Quran",
    translations: { Будь: "Be", добр: "kind", к: "to", своим: "your", соседям: "neighbors" },
  },
  {
    english: "Forgiveness is a noble quality",
    russian: "Прощение это благородное качество",
    source: "The Quran",
    translations: { Прощение: "Forgiveness", это: "is", благородное: "noble", качество: "quality" },
  },
  {
    english: "Your wealth is what you give",
    russian: "Твое богатство это то что ты даешь",
    source: "The Quran",
    translations: { Твое: "Your", богатство: "wealth", это: "is", то: "what", что: "that", ты: "you", даешь: "give" },
  },

  // Bible (15)
  {
    english: "Love your neighbor as yourself",
    russian: "Люби ближнего своего как самого себя",
    source: "The Bible",
    translations: { Люби: "Love", ближнего: "neighbor", своего: "your", как: "as", самого: "same", себя: "yourself" },
  },
  {
    english: "Do unto others as you would have them do",
    russian: "Поступай с другими так как хочешь чтобы поступали",
    source: "The Bible",
    translations: {
      Поступай: "Do",
      с: "unto",
      другими: "others",
      так: "as",
      как: "as",
      хочешь: "you would",
      чтобы: "have them",
      поступали: "do",
    },
  },
  {
    english: "Faith can move mountains",
    russian: "Вера может двигать горы",
    source: "The Bible",
    translations: { Вера: "Faith", может: "can", двигать: "move", горы: "mountains" },
  },
  {
    english: "The truth shall set you free",
    russian: "Истина освободит вас",
    source: "The Bible",
    translations: { Истина: "The truth", освободит: "shall set free", вас: "you" },
  },
  {
    english: "Ask and you shall receive",
    russian: "Проси и получишь",
    source: "The Bible",
    translations: { Проси: "Ask", и: "and", получишь: "you shall receive" },
  },
  {
    english: "Judge not lest you be judged",
    russian: "Не суди чтобы не быть судимым",
    source: "The Bible",
    translations: { Не: "not", суди: "Judge", чтобы: "lest", не: "not", быть: "be", судимым: "judged" },
  },
  {
    english: "Blessed are the peacemakers",
    russian: "Блаженны миротворцы",
    source: "The Bible",
    translations: { Блаженны: "Blessed", миротворцы: "the peacemakers" },
  },
  {
    english: "Let there be light",
    russian: "Да будет свет",
    source: "The Bible",
    translations: { Да: "Let", будет: "there be", свет: "light" },
  },
  {
    english: "Man does not live by bread alone",
    russian: "Не хлебом единым жив человек",
    source: "The Bible",
    translations: { Не: "not", хлебом: "by bread", единым: "alone", жив: "live", человек: "Man" },
  },
  {
    english: "Love is patient and kind",
    russian: "Любовь терпелива и добра",
    source: "The Bible",
    translations: { Любовь: "Love", терпелива: "is patient", и: "and", добра: "kind" },
  },
  {
    english: "The meek shall inherit the earth",
    russian: "Кроткие наследуют землю",
    source: "The Bible",
    translations: { Кроткие: "The meek", наследуют: "shall inherit", землю: "the earth" },
  },
  {
    english: "As you sow, so shall you reap",
    russian: "Что посеешь то и пожнешь",
    source: "The Bible",
    translations: { Что: "As", посеешь: "you sow", то: "so", и: "shall", пожнешь: "you reap" },
  },
  {
    english: "A house divided cannot stand",
    russian: "Дом разделенный не устоит",
    source: "The Bible",
    translations: { Дом: "A house", разделенный: "divided", не: "cannot", устоит: "stand" },
  },
  {
    english: "Seek and you shall find",
    russian: "Ищите и найдете",
    source: "The Bible",
    translations: { Ищите: "Seek", и: "and", найдете: "you shall find" },
  },
  {
    english: "No one can serve two masters",
    russian: "Никто не может служить двум господам",
    source: "The Bible",
    translations: { Никто: "No one", не: "not", может: "can", служить: "serve", двум: "two", господам: "masters" },
  },

  // Talmud (15)
  {
    english: "Who is wise? One who learns from everyone",
    russian: "Кто мудр? Тот кто учится у всех",
    source: "The Talmud",
    translations: {
      Кто: "Who",
      мудр: "is wise",
      Тот: "One",
      кто: "who",
      учится: "learns",
      у: "from",
      всех: "everyone",
    },
  },
  {
    english: "Silence is a fence for wisdom",
    russian: "Молчание это ограда для мудрости",
    source: "The Talmud",
    translations: { Молчание: "Silence", это: "is", ограда: "fence", для: "for", мудрости: "wisdom" },
  },
  {
    english: "The highest form of wisdom is kindness",
    russian: "Высшая форма мудрости это доброта",
    source: "The Talmud",
    translations: { Высшая: "The highest", форма: "form", мудрости: "of wisdom", это: "is", доброта: "kindness" },
  },
  {
    english: "Save one life, save the world",
    russian: "Спаси одну жизнь спаси мир",
    source: "The Talmud",
    translations: { Спаси: "Save", одну: "one", жизнь: "life", спаси: "save", мир: "the world" },
  },
  {
    english: "Words should be weighed, not counted",
    russian: "Слова следует взвешивать а не считать",
    source: "The Talmud",
    translations: {
      Слова: "Words",
      следует: "should",
      взвешивать: "be weighed",
      а: "not",
      не: "not",
      считать: "counted",
    },
  },
  {
    english: "Do not be daunted by the task",
    russian: "Не пугайся задачи",
    source: "The Talmud",
    translations: { Не: "Do not", пугайся: "be daunted", задачи: "by the task" },
  },
  {
    english: "Teach your tongue to say I do not know",
    russian: "Научи свой язык говорить я не знаю",
    source: "The Talmud",
    translations: {
      Научи: "Teach",
      свой: "your",
      язык: "tongue",
      говорить: "to say",
      я: "I",
      не: "do not",
      знаю: "know",
    },
  },
  {
    english: "A person is judged by their deeds",
    russian: "Человека судят по его делам",
    source: "The Talmud",
    translations: { Человека: "A person", судят: "is judged", по: "by", его: "their", делам: "deeds" },
  },
  {
    english: "The day is short and the work is great",
    russian: "День короток а работа велика",
    source: "The Talmud",
    translations: { День: "The day", короток: "is short", а: "and", работа: "the work", велика: "is great" },
  },
  {
    english: "Make your home a meeting place for scholars",
    russian: "Сделай свой дом местом встречи ученых",
    source: "The Talmud",
    translations: {
      Сделай: "Make",
      свой: "your",
      дом: "home",
      местом: "place",
      встречи: "of meeting",
      ученых: "for scholars",
    },
  },
  {
    english: "If I am not for myself, who will be?",
    russian: "Если я не за себя кто будет?",
    source: "The Talmud",
    translations: { Если: "If", я: "I", не: "not", за: "for", себя: "myself", кто: "who", будет: "will be" },
  },
  {
    english: "Where there is no vision, people perish",
    russian: "Где нет видения люди погибают",
    source: "The Talmud",
    translations: { Где: "Where", нет: "there is no", видения: "vision", люди: "people", погибают: "perish" },
  },
  {
    english: "Great is peace, for all blessings are in it",
    russian: "Велик мир ибо в нем все благословения",
    source: "The Talmud",
    translations: {
      Велик: "Great",
      мир: "is peace",
      ибо: "for",
      в: "in",
      нем: "it",
      все: "all",
      благословения: "blessings",
    },
  },
  {
    english: "He who saves one soul saves the universe",
    russian: "Кто спасает одну душу спасает вселенную",
    source: "The Talmud",
    translations: {
      Кто: "He who",
      спасает: "saves",
      одну: "one",
      душу: "soul",
      спасает: "saves",
      вселенную: "the universe",
    },
  },
  {
    english: "The bashful cannot learn",
    russian: "Застенчивый не может учиться",
    source: "The Talmud",
    translations: { Застенчивый: "The bashful", не: "cannot", может: "can", учиться: "learn" },
  },

  // US Bill of Rights (5)
  {
    english: "Freedom of speech shall not be abridged",
    russian: "Свобода слова не должна ограничиваться",
    source: "US Bill of Rights",
    translations: { Свобода: "Freedom", слова: "of speech", не: "not", должна: "shall", ограничиваться: "be abridged" },
  },
  {
    english: "The right of the people to assemble",
    russian: "Право народа собираться",
    source: "US Bill of Rights",
    translations: { Право: "The right", народа: "of the people", собираться: "to assemble" },
  },
  {
    english: "No person shall be deprived of liberty",
    russian: "Никто не может быть лишен свободы",
    source: "US Bill of Rights",
    translations: {
      Никто: "No person",
      не: "not",
      может: "shall",
      быть: "be",
      лишен: "deprived",
      свободы: "of liberty",
    },
  },
  {
    english: "The right to a speedy trial",
    russian: "Право на скорый суд",
    source: "US Bill of Rights",
    translations: { Право: "The right", на: "to", скорый: "speedy", суд: "trial" },
  },
  {
    english: "Freedom of religion shall be protected",
    russian: "Свобода религии должна быть защищена",
    source: "US Bill of Rights",
    translations: { Свобода: "Freedom", религии: "of religion", должна: "shall", быть: "be", защищена: "protected" },
  },

  // US Declaration of Independence (5)
  {
    english: "All men are created equal",
    russian: "Все люди созданы равными",
    source: "US Declaration of Independence",
    translations: { Все: "All", люди: "men", созданы: "are created", равными: "equal" },
  },
  {
    english: "Life, liberty and the pursuit of happiness",
    russian: "Жизнь свобода и стремление к счастью",
    source: "US Declaration of Independence",
    translations: {
      Жизнь: "Life",
      свобода: "liberty",
      и: "and",
      стремление: "the pursuit",
      к: "of",
      счастью: "happiness",
    },
  },
  {
    english: "Government derives power from the governed",
    russian: "Правительство получает власть от управляемых",
    source: "US Declaration of Independence",
    translations: {
      Правительство: "Government",
      получает: "derives",
      власть: "power",
      от: "from",
      управляемых: "the governed",
    },
  },
  {
    english: "We hold these truths to be self-evident",
    russian: "Мы считаем эти истины самоочевидными",
    source: "US Declaration of Independence",
    translations: { Мы: "We", считаем: "hold", эти: "these", истины: "truths", самоочевидными: "to be self-evident" },
  },
  {
    english: "Unalienable rights endowed by their Creator",
    russian: "Неотъемлемые права дарованные их Создателем",
    source: "US Declaration of Independence",
    translations: {
      Неотъемлемые: "Unalienable",
      права: "rights",
      дарованные: "endowed",
      их: "by their",
      Создателем: "Creator",
    },
  },

  // Mao's Little Red Book (10)
  {
    english: "Power comes from the barrel of a gun",
    russian: "Власть исходит из ствола ружья",
    source: "Mao's Little Red Book",
    translations: { Власть: "Power", исходит: "comes", из: "from", ствола: "the barrel", ружья: "of a gun" },
  },
  {
    english: "A revolution is not a dinner party",
    russian: "Революция это не званый обед",
    source: "Mao's Little Red Book",
    translations: { Революция: "A revolution", это: "is", не: "not", званый: "dinner", обед: "party" },
  },
  {
    english: "Serve the people",
    russian: "Служите народу",
    source: "Mao's Little Red Book",
    translations: { Служите: "Serve", народу: "the people" },
  },
  {
    english: "Practice is the sole criterion of truth",
    russian: "Практика это единственный критерий истины",
    source: "Mao's Little Red Book",
    translations: {
      Практика: "Practice",
      это: "is",
      единственный: "the sole",
      критерий: "criterion",
      истины: "of truth",
    },
  },
  {
    english: "Dare to struggle, dare to win",
    russian: "Смей бороться смей побеждать",
    source: "Mao's Little Red Book",
    translations: { Смей: "Dare", бороться: "to struggle", смей: "dare", побеждать: "to win" },
  },
  {
    english: "Women hold up half the sky",
    russian: "Женщины держат половину неба",
    source: "Mao's Little Red Book",
    translations: { Женщины: "Women", держат: "hold up", половину: "half", неба: "the sky" },
  },
  {
    english: "To rebel is justified",
    russian: "Восставать оправдано",
    source: "Mao's Little Red Book",
    translations: { Восставать: "To rebel", оправдано: "is justified" },
  },
  {
    english: "Let a hundred flowers bloom",
    russian: "Пусть расцветут сто цветов",
    source: "Mao's Little Red Book",
    translations: { Пусть: "Let", расцветут: "bloom", сто: "a hundred", цветов: "flowers" },
  },
  {
    english: "Be resolute, fear no sacrifice",
    russian: "Будь решителен не бойся жертв",
    source: "Mao's Little Red Book",
    translations: { Будь: "Be", решителен: "resolute", не: "no", бойся: "fear", жертв: "sacrifice" },
  },
  {
    english: "Unite to win still greater victories",
    russian: "Объединяйтесь чтобы одержать еще большие победы",
    source: "Mao's Little Red Book",
    translations: {
      Объединяйтесь: "Unite",
      чтобы: "to",
      одержать: "win",
      еще: "still",
      большие: "greater",
      победы: "victories",
    },
  },

  // Confucius (10)
  {
    english: "The superior man is modest in speech",
    russian: "Благородный человек скромен в речах",
    source: "Confucius",
    translations: { Благородный: "The superior", человек: "man", скромен: "is modest", в: "in", речах: "speech" },
  },
  {
    english: "Study the past to define the future",
    russian: "Изучай прошлое чтобы определить будущее",
    source: "Confucius",
    translations: { Изучай: "Study", прошлое: "the past", чтобы: "to", определить: "define", будущее: "the future" },
  },
  {
    english: "It does not matter how slowly you go",
    russian: "Не важно как медленно ты идешь",
    source: "Confucius",
    translations: { Не: "It does not", важно: "matter", как: "how", медленно: "slowly", ты: "you", идешь: "go" },
  },
  {
    english: "Real knowledge is to know one's ignorance",
    russian: "Истинное знание это знать свое невежество",
    source: "Confucius",
    translations: {
      Истинное: "Real",
      знание: "knowledge",
      это: "is",
      знать: "to know",
      свое: "one's",
      невежество: "ignorance",
    },
  },
  {
    english: "Choose a job you love",
    russian: "Выбери работу которую любишь",
    source: "Confucius",
    translations: { Выбери: "Choose", работу: "a job", которую: "that", любишь: "you love" },
  },
  {
    english: "By three methods we may learn wisdom",
    russian: "Тремя способами мы можем учиться мудрости",
    source: "Confucius",
    translations: {
      Тремя: "By three",
      способами: "methods",
      мы: "we",
      можем: "may",
      учиться: "learn",
      мудрости: "wisdom",
    },
  },
  {
    english: "To see what is right and not do it",
    russian: "Видеть что правильно и не делать это",
    source: "Confucius",
    translations: {
      Видеть: "To see",
      что: "what",
      правильно: "is right",
      и: "and",
      не: "not",
      делать: "do",
      это: "it",
    },
  },
  {
    english: "Respect yourself and others will respect you",
    russian: "Уважай себя и другие будут уважать тебя",
    source: "Confucius",
    translations: {
      Уважай: "Respect",
      себя: "yourself",
      и: "and",
      другие: "others",
      будут: "will",
      уважать: "respect",
      тебя: "you",
    },
  },
  {
    english: "Our greatest glory is in rising after falling",
    russian: "Наша величайшая слава в подъеме после падения",
    source: "Confucius",
    translations: {
      Наша: "Our",
      величайшая: "greatest",
      слава: "glory",
      в: "is in",
      подъеме: "rising",
      после: "after",
      падения: "falling",
    },
  },
  {
    english: "When anger rises, think of the consequences",
    russian: "Когда гнев поднимается думай о последствиях",
    source: "Confucius",
    translations: {
      Когда: "When",
      гнев: "anger",
      поднимается: "rises",
      думай: "think",
      о: "of",
      последствиях: "the consequences",
    },
  },

  // Bhagavad Gita (10)
  {
    english: "You have the right to work only",
    russian: "У тебя есть право только на труд",
    source: "Bhagavad Gita",
    translations: { У: "at", тебя: "You", есть: "have", право: "the right", только: "only", на: "to", труд: "work" },
  },
  {
    english: "The soul is neither born nor does it die",
    russian: "Душа не рождается и не умирает",
    source: "Bhagavad Gita",
    translations: { Душа: "The soul", не: "neither", рождается: "born", и: "nor", не: "does it", умирает: "die" },
  },
  {
    english: "Change is the law of the universe",
    russian: "Изменение это закон вселенной",
    source: "Bhagavad Gita",
    translations: { Изменение: "Change", это: "is", закон: "the law", вселенной: "of the universe" },
  },
  {
    english: "Set thy heart upon thy work",
    russian: "Направь свое сердце на свою работу",
    source: "Bhagavad Gita",
    translations: { Направь: "Set", свое: "thy", сердце: "heart", на: "upon", свою: "thy", работу: "work" },
  },
  {
    english: "A man is made by his beliefs",
    russian: "Человек создан своими убеждениями",
    source: "Bhagavad Gita",
    translations: { Человек: "A man", создан: "is made", своими: "by his", убеждениями: "beliefs" },
  },
  {
    english: "The mind is restless and difficult to control",
    russian: "Ум беспокоен и труден для контроля",
    source: "Bhagavad Gita",
    translations: {
      Ум: "The mind",
      беспокоен: "is restless",
      и: "and",
      труден: "difficult",
      для: "to",
      контроля: "control",
    },
  },
  {
    english: "Hell has three gates: lust, anger, greed",
    russian: "У ада три врата: похоть гнев жадность",
    source: "Bhagavad Gita",
    translations: {
      У: "has",
      ада: "Hell",
      три: "three",
      врата: "gates",
      похоть: "lust",
      гнев: "anger",
      жадность: "greed",
    },
  },
  {
    english: "As they approach me, so I receive them",
    russian: "Как они приближаются ко мне так я принимаю их",
    source: "Bhagavad Gita",
    translations: {
      Как: "As",
      они: "they",
      приближаются: "approach",
      ко: "to",
      мне: "me",
      так: "so",
      я: "I",
      принимаю: "receive",
      их: "them",
    },
  },
  {
    english: "I am time, the destroyer of worlds",
    russian: "Я время разрушитель миров",
    source: "Bhagavad Gita",
    translations: { Я: "I am", время: "time", разрушитель: "the destroyer", миров: "of worlds" },
  },
  {
    english: "Those who are free from pride succeed",
    russian: "Те кто свободны от гордыни преуспевают",
    source: "Bhagavad Gita",
    translations: {
      Те: "Those",
      кто: "who",
      свободны: "are free",
      от: "from",
      гордыни: "pride",
      преуспевают: "succeed",
    },
  },

  // Karl Marx (10)
  {
    english: "Workers of the world, unite!",
    russian: "Пролетарии всех стран объединяйтесь!",
    source: "Karl Marx",
    translations: { Пролетарии: "Workers", всех: "of the world", стран: "countries", объединяйтесь: "unite" },
  },
  {
    english: "History repeats itself, first as tragedy",
    russian: "История повторяется сначала как трагедия",
    source: "Karl Marx",
    translations: {
      История: "History",
      повторяется: "repeats itself",
      сначала: "first",
      как: "as",
      трагедия: "tragedy",
    },
  },
  {
    english: "From each according to ability",
    russian: "От каждого по способностям",
    source: "Karl Marx",
    translations: { От: "From", каждого: "each", по: "according to", способностям: "ability" },
  },
  {
    english: "Religion is the opium of the people",
    russian: "Религия это опиум народа",
    source: "Karl Marx",
    translations: { Религия: "Religion", это: "is", опиум: "the opium", народа: "of the people" },
  },
  {
    english: "The philosophers have only interpreted the world",
    russian: "Философы лишь объясняли мир",
    source: "Karl Marx",
    translations: { Философы: "The philosophers", лишь: "only", объясняли: "interpreted", мир: "the world" },
  },
  {
    english: "Social progress can be measured",
    russian: "Социальный прогресс можно измерить",
    source: "Karl Marx",
    translations: { Социальный: "Social", прогресс: "progress", можно: "can", измерить: "be measured" },
  },
  {
    english: "The ruling ideas are the ideas of the ruling class",
    russian: "Господствующие идеи это идеи господствующего класса",
    source: "Karl Marx",
    translations: {
      Господствующие: "The ruling",
      идеи: "ideas",
      это: "are",
      идеи: "the ideas",
      господствующего: "of the ruling",
      класса: "class",
    },
  },
  {
    english: "Reason has always existed",
    russian: "Разум всегда существовал",
    source: "Karl Marx",
    translations: { Разум: "Reason", всегда: "always", существовал: "existed" },
  },
  {
    english: "Democracy is the road to socialism",
    russian: "Демократия это дорога к социализму",
    source: "Karl Marx",
    translations: { Демократия: "Democracy", это: "is", дорога: "the road", к: "to", социализму: "socialism" },
  },
  {
    english: "Nothing can have value without being useful",
    russian: "Ничто не может иметь ценности не будучи полезным",
    source: "Karl Marx",
    translations: {
      Ничто: "Nothing",
      не: "not",
      может: "can",
      иметь: "have",
      ценности: "value",
      не: "without",
      будучи: "being",
      полезным: "useful",
    },
  },

  // Vladimir Lenin (10)
  {
    english: "Trust is good, control is better",
    russian: "Доверяй но проверяй",
    source: "Vladimir Lenin",
    translations: { Доверяй: "Trust", но: "but", проверяй: "verify" },
  },
  {
    english: "There are no morals in politics",
    russian: "В политике нет морали",
    source: "Vladimir Lenin",
    translations: { В: "in", политике: "politics", нет: "no", морали: "morals" },
  },
  {
    english: "The best way to destroy the enemy",
    russian: "Лучший способ уничтожить врага",
    source: "Vladimir Lenin",
    translations: { Лучший: "The best", способ: "way", уничтожить: "to destroy", врага: "the enemy" },
  },
  {
    english: "Freedom is precious, so precious",
    russian: "Свобода драгоценна настолько драгоценна",
    source: "Vladimir Lenin",
    translations: { Свобода: "Freedom", драгоценна: "is precious", настолько: "so", драгоценна: "precious" },
  },
  {
    english: "He who does not work shall not eat",
    russian: "Кто не работает тот не ест",
    source: "Vladimir Lenin",
    translations: { Кто: "He who", не: "not", работает: "work", тот: "shall", не: "not", ест: "eat" },
  },
  {
    english: "One must always try to be revolutionary",
    russian: "Всегда нужно стараться быть революционным",
    source: "Vladimir Lenin",
    translations: { Всегда: "always", нужно: "must", стараться: "try", быть: "to be", революционным: "revolutionary" },
  },
  {
    english: "Every cook can govern",
    russian: "Каждая кухарка может управлять",
    source: "Vladimir Lenin",
    translations: { Каждая: "Every", кухарка: "cook", может: "can", управлять: "govern" },
  },
  {
    english: "Without revolutionary theory there is no movement",
    russian: "Без революционной теории нет движения",
    source: "Vladimir Lenin",
    translations: {
      Без: "Without",
      революционной: "revolutionary",
      теории: "theory",
      нет: "there is no",
      движения: "movement",
    },
  },
  {
    english: "Unity is a great thing",
    russian: "Единство это великое дело",
    source: "Vladimir Lenin",
    translations: { Единство: "Unity", это: "is", великое: "a great", дело: "thing" },
  },
  {
    english: "Learning is never done without errors",
    russian: "Обучение никогда не обходится без ошибок",
    source: "Vladimir Lenin",
    translations: {
      Обучение: "Learning",
      никогда: "never",
      не: "not",
      обходится: "is done",
      без: "without",
      ошибок: "errors",
    },
  },

  // Albert Einstein (5)
  {
    english: "Imagination is more important than knowledge",
    russian: "Воображение важнее знания",
    source: "Albert Einstein",
    translations: { Воображение: "Imagination", важнее: "is more important than", знания: "knowledge" },
  },
  {
    english: "Life is like riding a bicycle",
    russian: "Жизнь как езда на велосипеде",
    source: "Albert Einstein",
    translations: { Жизнь: "Life", как: "is like", езда: "riding", на: "on", велосипеде: "bicycle" },
  },
  {
    english: "The important thing is not to stop questioning",
    russian: "Важно не переставать задавать вопросы",
    source: "Albert Einstein",
    translations: {
      Важно: "The important thing",
      не: "not",
      переставать: "to stop",
      задавать: "questioning",
      вопросы: "questions",
    },
  },
  {
    english: "Try not to become a person of success",
    russian: "Старайся не стать человеком успеха",
    source: "Albert Einstein",
    translations: { Старайся: "Try", не: "not", стать: "to become", человеком: "a person", успеха: "of success" },
  },
  {
    english: "A person who never made a mistake",
    russian: "Человек который никогда не ошибался",
    source: "Albert Einstein",
    translations: { Человек: "A person", который: "who", никогда: "never", не: "not", ошибался: "made a mistake" },
  },

  // Humorous observations (20)
  {
    english: "I told my wife she was drawing her eyebrows too high",
    russian: "Я сказал жене что она рисует брови слишком высоко",
    source: "Humor",
    translations: {
      Я: "I",
      сказал: "told",
      жене: "my wife",
      что: "that",
      она: "she",
      рисует: "was drawing",
      брови: "her eyebrows",
      слишком: "too",
      высоко: "high",
    },
  },
  {
    english: "I'm on a seafood diet, I see food and I eat it",
    russian: "Я на морской диете я вижу еду и ем ее",
    source: "Humor",
    translations: {
      Я: "I",
      на: "on",
      морской: "seafood",
      диете: "diet",
      я: "I",
      вижу: "see",
      еду: "food",
      и: "and",
      ем: "eat",
      ее: "it",
    },
  },
  {
    english: "Why don't scientists trust atoms?",
    russian: "Почему ученые не доверяют атомам?",
    source: "Humor",
    translations: { Почему: "Why", ученые: "scientists", не: "don't", доверяют: "trust", атомам: "atoms" },
  },
  {
    english: "I used to be indecisive, now I'm not sure",
    russian: "Раньше я был нерешительным теперь не уверен",
    source: "Humor",
    translations: {
      Раньше: "I used to",
      я: "I",
      был: "be",
      нерешительным: "indecisive",
      теперь: "now",
      не: "not",
      уверен: "sure",
    },
  },
  {
    english: "I'm reading a book about anti-gravity",
    russian: "Я читаю книгу об антигравитации",
    source: "Humor",
    translations: { Я: "I'm", читаю: "reading", книгу: "a book", об: "about", антигравитации: "anti-gravity" },
  },
  {
    english: "The early bird might get the worm",
    russian: "Ранняя птица может поймать червя",
    source: "Humor",
    translations: { Ранняя: "The early", птица: "bird", может: "might", поймать: "get", червя: "the worm" },
  },
  {
    english: "I'm not arguing, I'm just explaining why I'm right",
    russian: "Я не спорю я просто объясняю почему прав",
    source: "Humor",
    translations: {
      Я: "I",
      не: "not",
      спорю: "arguing",
      я: "I",
      просто: "just",
      объясняю: "explaining",
      почему: "why",
      прав: "I'm right",
    },
  },
  {
    english: "The problem with troubleshooting is trouble shoots back",
    russian: "Проблема с устранением неполадок в том что неполадки стреляют обратно",
    source: "Humor",
    translations: {
      Проблема: "The problem",
      с: "with",
      устранением: "troubleshooting",
      неполадок: "trouble",
      в: "is",
      том: "that",
      что: "that",
      неполадки: "trouble",
      стреляют: "shoots",
      обратно: "back",
    },
  },
  {
    english: "I stayed up all night wondering where the sun went",
    russian: "Я не спал всю ночь гадая куда ушло солнце",
    source: "Humor",
    translations: {
      Я: "I",
      не: "not",
      спал: "slept",
      всю: "all",
      ночь: "night",
      гадая: "wondering",
      куда: "where",
      ушло: "went",
      солнце: "the sun",
    },
  },
  {
    english: "Common sense is like deodorant",
    russian: "Здравый смысл как дезодорант",
    source: "Humor",
    translations: { Здравый: "Common", смысл: "sense", как: "is like", дезодорант: "deodorant" },
  },
  {
    english: "Time flies like an arrow",
    russian: "Время летит как стрела",
    source: "Humor",
    translations: { Время: "Time", летит: "flies", как: "like", стрела: "an arrow" },
  },
  {
    english: "I'm not lazy, I'm on energy-saving mode",
    russian: "Я не ленивый я в режиме энергосбережения",
    source: "Humor",
    translations: {
      Я: "I",
      не: "not",
      ленивый: "lazy",
      я: "I'm",
      в: "in",
      режиме: "mode",
      энергосбережения: "energy-saving",
    },
  },
  {
    english: "My bed is a magical place where I suddenly remember everything",
    russian: "Моя кровать это волшебное место где я вдруг все вспоминаю",
    source: "Humor",
    translations: {
      Моя: "My",
      кровать: "bed",
      это: "is",
      волшебное: "a magical",
      место: "place",
      где: "where",
      я: "I",
      вдруг: "suddenly",
      все: "everything",
      вспоминаю: "remember",
    },
  },
  {
    english: "I'd agree with you but then we'd both be wrong",
    russian: "Я бы согласился с тобой но тогда мы оба ошибались бы",
    source: "Humor",
    translations: {
      Я: "I",
      бы: "would",
      согласился: "agree",
      с: "with",
      тобой: "you",
      но: "but",
      тогда: "then",
      мы: "we",
      оба: "both",
      ошибались: "be",
      бы: "wrong",
    },
  },
  {
    english: "The best time to plant a tree was yesterday",
    russian: "Лучшее время посадить дерево было вчера",
    source: "Humor",
    translations: {
      Лучшее: "The best",
      время: "time",
      посадить: "to plant",
      дерево: "a tree",
      было: "was",
      вчера: "yesterday",
    },
  },
  {
    english: "I don't need anger management",
    russian: "Мне не нужен контроль гнева",
    source: "Humor",
    translations: { Мне: "I", не: "don't", нужен: "need", контроль: "management", гнева: "anger" },
  },
  {
    english: "My wallet is like an onion",
    russian: "Мой кошелек как лук",
    source: "Humor",
    translations: { Мой: "My", кошелек: "wallet", как: "is like", лук: "an onion" },
  },
  {
    english: "I'm not short, I'm concentrated awesome",
    russian: "Я не низкий я концентрированная крутость",
    source: "Humor",
    translations: {
      Я: "I'm",
      не: "not",
      низкий: "short",
      я: "I'm",
      концентрированная: "concentrated",
      крутость: "awesome",
    },
  },
  {
    english: "Coffee: because adulting is hard",
    russian: "Кофе потому что быть взрослым трудно",
    source: "Humor",
    translations: {
      Кофе: "Coffee",
      потому: "because",
      что: "that",
      быть: "being",
      взрослым: "adult",
      трудно: "is hard",
    },
  },
  {
    english: "If you think nobody cares, try missing payments",
    russian: "Если думаешь что никому нет дела попробуй пропустить платежи",
    source: "Humor",
    translations: {
      Если: "If",
      думаешь: "you think",
      что: "that",
      никому: "nobody",
      нет: "no",
      дела: "cares",
      попробуй: "try",
      пропустить: "missing",
      платежи: "payments",
    },
  },

  // Shakespeare (10)
  {
    english: "To be, or not to be, that is the question",
    russian: "Быть или не быть вот в чем вопрос",
    source: "Shakespeare",
    translations: {
      Быть: "To be",
      или: "or",
      не: "not",
      быть: "to be",
      вот: "that",
      в: "is",
      чем: "what",
      вопрос: "the question",
    },
  },
  {
    english: "All the world's a stage",
    russian: "Весь мир театр",
    source: "Shakespeare",
    translations: { Весь: "All", мир: "the world", театр: "a stage" },
  },
  {
    english: "Love all, trust a few, do wrong to none",
    russian: "Люби всех доверяй немногим не обижай никого",
    source: "Shakespeare",
    translations: {
      Люби: "Love",
      всех: "all",
      доверяй: "trust",
      немногим: "a few",
      не: "do not",
      обижай: "wrong",
      никого: "none",
    },
  },
  {
    english: "The course of true love never did run smooth",
    russian: "Путь истинной любви никогда не был гладким",
    source: "Shakespeare",
    translations: {
      Путь: "The course",
      истинной: "of true",
      любви: "love",
      никогда: "never",
      не: "not",
      был: "did",
      гладким: "run smooth",
    },
  },
  {
    english: "Brevity is the soul of wit",
    russian: "Краткость душа ума",
    source: "Shakespeare",
    translations: { Краткость: "Brevity", душа: "is the soul", ума: "of wit" },
  },
  {
    english: "This above all: to thine own self be true",
    russian: "Прежде всего будь верен самому себе",
    source: "Shakespeare",
    translations: { Прежде: "This above", всего: "all", будь: "be", верен: "true", самому: "to own", себе: "self" },
  },
  {
    english: "Some are born great, some achieve greatness",
    russian: "Одни рождаются великими другие достигают величия",
    source: "Shakespeare",
    translations: {
      Одни: "Some",
      рождаются: "are born",
      великими: "great",
      другие: "some",
      достигают: "achieve",
      величия: "greatness",
    },
  },
  {
    english: "What's in a name? That which we call a rose",
    russian: "Что в имени? То что мы зовем розой",
    source: "Shakespeare",
    translations: {
      Что: "What",
      в: "in",
      имени: "a name",
      То: "That",
      что: "which",
      мы: "we",
      зовем: "call",
      розой: "a rose",
    },
  },
  {
    english: "The lady doth protest too much",
    russian: "Леди протестует слишком много",
    source: "Shakespeare",
    translations: { Леди: "The lady", протестует: "doth protest", слишком: "too", много: "much" },
  },
  {
    english: "We know what we are, but not what we may be",
    russian: "Мы знаем кто мы но не кем можем стать",
    source: "Shakespeare",
    translations: {
      Мы: "We",
      знаем: "know",
      кто: "what",
      мы: "we are",
      но: "but",
      не: "not",
      кем: "what",
      можем: "we may",
      стать: "be",
    },
  },

  // Mark Twain (10)
  {
    english: "The secret of getting ahead is getting started",
    russian: "Секрет движения вперед в том чтобы начать",
    source: "Mark Twain",
    translations: {
      Секрет: "The secret",
      движения: "of getting",
      вперед: "ahead",
      в: "is",
      том: "that",
      чтобы: "to",
      начать: "getting started",
    },
  },
  {
    english: "Never put off till tomorrow what you can do today",
    russian: "Никогда не откладывай на завтра то что можешь сделать сегодня",
    source: "Mark Twain",
    translations: {
      Никогда: "Never",
      не: "not",
      откладывай: "put off",
      на: "till",
      завтра: "tomorrow",
      то: "what",
      что: "that",
      можешь: "you can",
      сделать: "do",
      сегодня: "today",
    },
  },
  {
    english: "Kindness is the language the deaf can hear",
    russian: "Доброта это язык который глухие могут услышать",
    source: "Mark Twain",
    translations: {
      Доброта: "Kindness",
      это: "is",
      язык: "the language",
      который: "that",
      глухие: "the deaf",
      могут: "can",
      услышать: "hear",
    },
  },
  {
    english: "The two most important days in your life",
    russian: "Два самых важных дня в твоей жизни",
    source: "Mark Twain",
    translations: {
      Два: "The two",
      самых: "most",
      важных: "important",
      дня: "days",
      в: "in",
      твоей: "your",
      жизни: "life",
    },
  },
  {
    english: "If you tell the truth, you don't have to remember",
    russian: "Если говоришь правду не нужно помнить",
    source: "Mark Twain",
    translations: {
      Если: "If",
      говоришь: "you tell",
      правду: "the truth",
      не: "don't",
      нужно: "have to",
      помнить: "remember",
    },
  },
  {
    english: "Better to remain silent and be thought a fool",
    russian: "Лучше молчать и казаться глупцом",
    source: "Mark Twain",
    translations: { Лучше: "Better", молчать: "to remain silent", и: "and", казаться: "be thought", глупцом: "a fool" },
  },
  {
    english: "A lie can travel halfway around the world",
    russian: "Ложь может облететь полмира",
    source: "Mark Twain",
    translations: { Ложь: "A lie", может: "can", облететь: "travel around", полмира: "halfway world" },
  },
  {
    english: "Good friends, good books, and a sleepy conscience",
    russian: "Хорошие друзья хорошие книги и спокойная совесть",
    source: "Mark Twain",
    translations: {
      Хорошие: "Good",
      друзья: "friends",
      хорошие: "good",
      книги: "books",
      и: "and",
      спокойная: "sleepy",
      совесть: "conscience",
    },
  },
  {
    english: "Anger is an acid that does more harm",
    russian: "Гнев это кислота которая вредит больше",
    source: "Mark Twain",
    translations: {
      Гнев: "Anger",
      это: "is",
      кислота: "an acid",
      которая: "that",
      вредит: "does harm",
      больше: "more",
    },
  },
  {
    english: "Courage is resistance to fear",
    russian: "Мужество это сопротивление страху",
    source: "Mark Twain",
    translations: { Мужество: "Courage", это: "is", сопротивление: "resistance", страху: "to fear" },
  },

  // Winston Churchill (5)
  {
    english: "Success is not final, failure is not fatal",
    russian: "Успех не окончателен неудача не фатальна",
    source: "Winston Churchill",
    translations: {
      Успех: "Success",
      не: "not",
      окончателен: "final",
      неудача: "failure",
      не: "not",
      фатальна: "fatal",
    },
  },
  {
    english: "If you're going through hell, keep going",
    russian: "Если проходишь через ад продолжай идти",
    source: "Winston Churchill",
    translations: {
      Если: "If",
      проходишь: "you're going",
      через: "through",
      ад: "hell",
      продолжай: "keep",
      идти: "going",
    },
  },
  {
    english: "We make a living by what we get",
    russian: "Мы зарабатываем на жизнь тем что получаем",
    source: "Winston Churchill",
    translations: {
      Мы: "We",
      зарабатываем: "make",
      на: "a",
      жизнь: "living",
      тем: "by",
      что: "what",
      получаем: "we get",
    },
  },
  {
    english: "Attitude is a little thing that makes difference",
    russian: "Отношение это малая вещь которая делает разницу",
    source: "Winston Churchill",
    translations: {
      Отношение: "Attitude",
      это: "is",
      малая: "a little",
      вещь: "thing",
      которая: "that",
      делает: "makes",
      разницу: "difference",
    },
  },
  {
    english: "The price of greatness is responsibility",
    russian: "Цена величия это ответственность",
    source: "Winston Churchill",
    translations: { Цена: "The price", величия: "of greatness", это: "is", ответственность: "responsibility" },
  },

  // Oscar Wilde (10)
  {
    english: "Be yourself; everyone else is already taken",
    russian: "Будь собой все остальные уже заняты",
    source: "Oscar Wilde",
    translations: {
      Будь: "Be",
      собой: "yourself",
      все: "everyone",
      остальные: "else",
      уже: "already",
      заняты: "taken",
    },
  },
  {
    english: "To live is the rarest thing in the world",
    russian: "Жить это самая редкая вещь в мире",
    source: "Oscar Wilde",
    translations: {
      Жить: "To live",
      это: "is",
      самая: "the rarest",
      редкая: "rare",
      вещь: "thing",
      в: "in",
      мире: "the world",
    },
  },
  {
    english: "I can resist everything except temptation",
    russian: "Я могу противостоять всему кроме искушения",
    source: "Oscar Wilde",
    translations: {
      Я: "I",
      могу: "can",
      противостоять: "resist",
      всему: "everything",
      кроме: "except",
      искушения: "temptation",
    },
  },
  {
    english: "Experience is the name we give our mistakes",
    russian: "Опыт это имя которое мы даем своим ошибкам",
    source: "Oscar Wilde",
    translations: {
      Опыт: "Experience",
      это: "is",
      имя: "the name",
      которое: "that",
      мы: "we",
      даем: "give",
      своим: "our",
      ошибкам: "mistakes",
    },
  },
  {
    english: "We are all in the gutter",
    russian: "Мы все в сточной канаве",
    source: "Oscar Wilde",
    translations: { Мы: "We", все: "are all", в: "in", сточной: "the", канаве: "gutter" },
  },
  {
    english: "Always forgive your enemies",
    russian: "Всегда прощай своих врагов",
    source: "Oscar Wilde",
    translations: { Всегда: "Always", прощай: "forgive", своих: "your", врагов: "enemies" },
  },
  {
    english: "The only way to get rid of temptation",
    russian: "Единственный способ избавиться от искушения",
    source: "Oscar Wilde",
    translations: {
      Единственный: "The only",
      способ: "way",
      избавиться: "to get rid",
      от: "of",
      искушения: "temptation",
    },
  },
  {
    english: "Life imitates art far more than art imitates life",
    russian: "Жизнь подражает искусству гораздо больше чем искусство жизни",
    source: "Oscar Wilde",
    translations: {
      Жизнь: "Life",
      подражает: "imitates",
      искусству: "art",
      гораздо: "far",
      больше: "more",
      чем: "than",
      искусство: "art",
      жизни: "life",
    },
  },
  {
    english: "True friends stab you in the front",
    russian: "Настоящие друзья бьют тебя спереди",
    source: "Oscar Wilde",
    translations: { Настоящие: "True", друзья: "friends", бьют: "stab", тебя: "you", спереди: "in the front" },
  },
  {
    english: "Quotation is a serviceable substitute for wit",
    russian: "Цитата это полезная замена остроумию",
    source: "Oscar Wilde",
    translations: {
      Цитата: "Quotation",
      это: "is",
      полезная: "serviceable",
      замена: "substitute",
      остроумию: "for wit",
    },
  },
]
