export const phrases = [
  // Quran (20)
  {
    english: "Speak kindly to all people.",
    french: "Parlez gentiment à tous les gens.",
    source: "—The Quran",
    wordTranslations: { parlez: "speak", gentiment: "kindly", à: "to", tous: "all", les: "the", gens: "people" },
  },
  {
    english: "Do good, for God loves those who do good.",
    french: "Faites le bien, car Dieu aime ceux qui font le bien.",
    source: "—The Quran",
    wordTranslations: {
      faites: "do",
      le: "the",
      bien: "good",
      car: "for",
      dieu: "god",
      aime: "loves",
      ceux: "those",
      qui: "who",
      font: "do",
    },
  },
  {
    english: "Patience is beautiful.",
    french: "La patience est belle.",
    source: "—The Quran",
    wordTranslations: { la: "the", patience: "patience", est: "is", belle: "beautiful" },
  },
  {
    english: "The truth stands clear from error.",
    french: "La vérité se distingue clairement de l'erreur.",
    source: "—The Quran",
    wordTranslations: {
      la: "the",
      vérité: "truth",
      se: "itself",
      distingue: "stands",
      clairement: "clear",
      de: "from",
      "l'erreur": "error",
    },
  },
  {
    english: "Seek knowledge from cradle to grave.",
    french: "Cherchez la connaissance du berceau à la tombe.",
    source: "—The Quran",
    wordTranslations: {
      cherchez: "seek",
      la: "the",
      connaissance: "knowledge",
      du: "from",
      berceau: "cradle",
      à: "to",
      tombe: "grave",
    },
  },
  {
    english: "God is with those who are patient.",
    french: "Dieu est avec ceux qui sont patients.",
    source: "—The Quran",
    wordTranslations: {
      dieu: "god",
      est: "is",
      avec: "with",
      ceux: "those",
      qui: "who",
      sont: "are",
      patients: "patient",
    },
  },
  {
    english: "The best among you are those who learn and teach.",
    french: "Les meilleurs d'entre vous sont ceux qui apprennent et enseignent.",
    source: "—The Quran",
    wordTranslations: {
      les: "the",
      meilleurs: "best",
      "d'entre": "among",
      vous: "you",
      sont: "are",
      ceux: "those",
      qui: "who",
      apprennent: "learn",
      et: "and",
      enseignent: "teach",
    },
  },
  {
    english: "Wealth and children are the adornment of life.",
    french: "La richesse et les enfants sont l'ornement de la vie.",
    source: "—The Quran",
    wordTranslations: {
      la: "the",
      richesse: "wealth",
      et: "and",
      les: "the",
      enfants: "children",
      sont: "are",
      "l'ornement": "adornment",
      de: "of",
      vie: "life",
    },
  },
  {
    english: "Give full measure when you measure.",
    french: "Donnez pleine mesure quand vous mesurez.",
    source: "—The Quran",
    wordTranslations: {
      donnez: "give",
      pleine: "full",
      mesure: "measure",
      quand: "when",
      vous: "you",
      mesurez: "measure",
    },
  },
  {
    english: "Whoever saves a life, saves all of humanity.",
    french: "Quiconque sauve une vie, sauve toute l'humanité.",
    source: "—The Quran",
    wordTranslations: {
      quiconque: "whoever",
      sauve: "saves",
      une: "a",
      vie: "life",
      toute: "all",
      "l'humanité": "humanity",
    },
  },
  {
    english: "Be just, for justice is nearest to piety.",
    french: "Soyez justes, car la justice est la plus proche de la piété.",
    source: "—The Quran",
    wordTranslations: {
      soyez: "be",
      justes: "just",
      car: "for",
      la: "the",
      justice: "justice",
      est: "is",
      plus: "more",
      proche: "near",
      de: "of",
      piété: "piety",
    },
  },
  {
    english: "Help one another in righteousness.",
    french: "Aidez-vous les uns les autres dans la droiture.",
    source: "—The Quran",
    wordTranslations: {
      "aidez-vous": "help",
      les: "the",
      uns: "one",
      autres: "another",
      dans: "in",
      la: "the",
      droiture: "righteousness",
    },
  },
  {
    english: "Forgive and overlook until God brings His command.",
    french: "Pardonnez et négligez jusqu'à ce que Dieu apporte son commandement.",
    source: "—The Quran",
    wordTranslations: {
      pardonnez: "forgive",
      et: "and",
      négligez: "overlook",
      "jusqu'à": "until",
      ce: "that",
      que: "that",
      dieu: "god",
      apporte: "brings",
      son: "his",
      commandement: "command",
    },
  },
  {
    english: "The reward of goodness is nothing but goodness.",
    french: "La récompense de la bonté n'est rien d'autre que la bonté.",
    source: "—The Quran",
    wordTranslations: {
      la: "the",
      récompense: "reward",
      de: "of",
      bonté: "goodness",
      "n'est": "is not",
      rien: "nothing",
      "d'autre": "other",
      que: "but",
    },
  },
  {
    english: "God does not burden a soul beyond its capacity.",
    french: "Dieu ne charge pas une âme au-delà de sa capacité.",
    source: "—The Quran",
    wordTranslations: {
      dieu: "god",
      ne: "not",
      charge: "burden",
      pas: "not",
      une: "a",
      âme: "soul",
      "au-delà": "beyond",
      de: "of",
      sa: "its",
      capacité: "capacity",
    },
  },
  {
    english: "Take counsel with them in all affairs.",
    french: "Consultez-les dans toutes les affaires.",
    source: "—The Quran",
    wordTranslations: { "consultez-les": "take counsel", dans: "in", toutes: "all", les: "the", affaires: "affairs" },
  },
  {
    english: "Repel evil with that which is better.",
    french: "Repoussez le mal par ce qui est meilleur.",
    source: "—The Quran",
    wordTranslations: {
      repoussez: "repel",
      le: "the",
      mal: "evil",
      par: "with",
      ce: "that",
      qui: "which",
      est: "is",
      meilleur: "better",
    },
  },
  {
    english: "Be steadfast in prayer and give in charity.",
    french: "Soyez constants dans la prière et donnez à la charité.",
    source: "—The Quran",
    wordTranslations: {
      soyez: "be",
      constants: "steadfast",
      dans: "in",
      la: "the",
      prière: "prayer",
      et: "and",
      donnez: "give",
      à: "in",
      charité: "charity",
    },
  },
  {
    english: "Whoever does good will benefit from it.",
    french: "Quiconque fait le bien en bénéficiera.",
    source: "—The Quran",
    wordTranslations: {
      quiconque: "whoever",
      fait: "does",
      le: "the",
      bien: "good",
      en: "from it",
      bénéficiera: "will benefit",
    },
  },
  {
    english: "Indeed, with hardship comes ease.",
    french: "En effet, avec la difficulté vient la facilité.",
    source: "—The Quran",
    wordTranslations: {
      en: "in",
      effet: "indeed",
      avec: "with",
      la: "the",
      difficulté: "hardship",
      vient: "comes",
      facilité: "ease",
    },
  },

  // Bible (20)
  {
    english: "Love your neighbor as yourself.",
    french: "Aimez votre prochain comme vous-même.",
    source: "—The Bible",
    wordTranslations: { aimez: "love", votre: "your", prochain: "neighbor", comme: "as", "vous-même": "yourself" },
  },
  {
    english: "Do unto others as you would have them do unto you.",
    french: "Faites aux autres ce que vous voudriez qu'ils vous fassent.",
    source: "—The Bible",
    wordTranslations: {
      faites: "do",
      aux: "unto",
      autres: "others",
      ce: "as",
      que: "that",
      vous: "you",
      voudriez: "would",
      "qu'ils": "they",
      fassent: "do",
    },
  },
  {
    english: "The truth shall set you free.",
    french: "La vérité vous rendra libres.",
    source: "—The Bible",
    wordTranslations: { la: "the", vérité: "truth", vous: "you", rendra: "shall set", libres: "free" },
  },
  {
    english: "Faith can move mountains.",
    french: "La foi peut déplacer les montagnes.",
    source: "—The Bible",
    wordTranslations: { la: "the", foi: "faith", peut: "can", déplacer: "move", les: "the", montagnes: "mountains" },
  },
  {
    english: "Judge not, lest ye be judged.",
    french: "Ne jugez pas, de peur que vous ne soyez jugés.",
    source: "—The Bible",
    wordTranslations: {
      ne: "not",
      jugez: "judge",
      pas: "not",
      de: "lest",
      peur: "fear",
      que: "that",
      vous: "you",
      soyez: "be",
      jugés: "judged",
    },
  },
  {
    english: "Let he who is without sin cast the first stone.",
    french: "Que celui qui est sans péché jette la première pierre.",
    source: "—The Bible",
    wordTranslations: {
      que: "let",
      celui: "he",
      qui: "who",
      est: "is",
      sans: "without",
      péché: "sin",
      jette: "cast",
      la: "the",
      première: "first",
      pierre: "stone",
    },
  },
  {
    english: "Ask and it shall be given to you.",
    french: "Demandez et il vous sera donné.",
    source: "—The Bible",
    wordTranslations: { demandez: "ask", et: "and", il: "it", vous: "you", sera: "shall be", donné: "given" },
  },
  {
    english: "The meek shall inherit the earth.",
    french: "Les doux hériteront de la terre.",
    source: "—The Bible",
    wordTranslations: { les: "the", doux: "meek", hériteront: "shall inherit", de: "of", la: "the", terre: "earth" },
  },
  {
    english: "Blessed are the peacemakers.",
    french: "Heureux sont les artisans de la paix.",
    source: "—The Bible",
    wordTranslations: {
      heureux: "blessed",
      sont: "are",
      les: "the",
      artisans: "makers",
      de: "of",
      la: "the",
      paix: "peace",
    },
  },
  {
    english: "Let there be light.",
    french: "Que la lumière soit.",
    source: "—The Bible",
    wordTranslations: { que: "let", la: "the", lumière: "light", soit: "be" },
  },
  {
    english: "Forgive them, for they know not what they do.",
    french: "Pardonnez-leur, car ils ne savent pas ce qu'ils font.",
    source: "—The Bible",
    wordTranslations: {
      "pardonnez-leur": "forgive them",
      car: "for",
      ils: "they",
      ne: "not",
      savent: "know",
      pas: "not",
      ce: "what",
      "qu'ils": "they",
      font: "do",
    },
  },
  {
    english: "Love is patient, love is kind.",
    french: "L'amour est patient, l'amour est bon.",
    source: "—The Bible",
    wordTranslations: { "l'amour": "love", est: "is", patient: "patient", bon: "kind" },
  },
  {
    english: "There is a time for everything under heaven.",
    french: "Il y a un temps pour tout sous le ciel.",
    source: "—The Bible",
    wordTranslations: {
      il: "there",
      y: "there",
      a: "is",
      un: "a",
      temps: "time",
      pour: "for",
      tout: "everything",
      sous: "under",
      le: "the",
      ciel: "heaven",
    },
  },
  {
    english: "Many are called, but few are chosen.",
    french: "Beaucoup sont appelés, mais peu sont choisis.",
    source: "—The Bible",
    wordTranslations: { beaucoup: "many", sont: "are", appelés: "called", mais: "but", peu: "few", choisis: "chosen" },
  },
  {
    english: "Turn the other cheek.",
    french: "Tourne l'autre joue.",
    source: "—The Bible",
    wordTranslations: { tourne: "turn", "l'autre": "the other", joue: "cheek" },
  },
  {
    english: "Be fruitful and multiply.",
    french: "Soyez féconds et multipliez-vous.",
    source: "—The Bible",
    wordTranslations: { soyez: "be", féconds: "fruitful", et: "and", "multipliez-vous": "multiply" },
  },
  {
    english: "The spirit is willing, but the flesh is weak.",
    french: "L'esprit est fort, mais la chair est faible.",
    source: "—The Bible",
    wordTranslations: {
      "l'esprit": "spirit",
      est: "is",
      fort: "willing",
      mais: "but",
      la: "the",
      chair: "flesh",
      faible: "weak",
    },
  },
  {
    english: "Cast your bread upon the waters.",
    french: "Jetez votre pain sur les eaux.",
    source: "—The Bible",
    wordTranslations: { jetez: "cast", votre: "your", pain: "bread", sur: "upon", les: "the", eaux: "waters" },
  },
  {
    english: "A house divided cannot stand.",
    french: "Une maison divisée ne peut pas tenir.",
    source: "—The Bible",
    wordTranslations: {
      une: "a",
      maison: "house",
      divisée: "divided",
      ne: "not",
      peut: "can",
      pas: "not",
      tenir: "stand",
    },
  },
  {
    english: "Seek and you shall find.",
    french: "Cherchez et vous trouverez.",
    source: "—The Bible",
    wordTranslations: { cherchez: "seek", et: "and", vous: "you", trouverez: "shall find" },
  },

  // Talmud (20)
  {
    english: "Who is wise? One who learns from every person.",
    french: "Qui est sage? Celui qui apprend de chaque personne.",
    source: "—The Talmud",
    wordTranslations: {
      qui: "who",
      est: "is",
      sage: "wise",
      celui: "one",
      apprend: "learns",
      de: "from",
      chaque: "every",
      personne: "person",
    },
  },
  {
    english: "Actions speak louder than words.",
    french: "Les actions parlent plus fort que les mots.",
    source: "—The Talmud",
    wordTranslations: {
      les: "the",
      actions: "actions",
      parlent: "speak",
      plus: "more",
      fort: "loud",
      que: "than",
      mots: "words",
    },
  },
  {
    english: "If I am not for myself, who will be for me?",
    french: "Si je ne suis pas pour moi, qui sera pour moi?",
    source: "—The Talmud",
    wordTranslations: {
      si: "if",
      je: "I",
      ne: "not",
      suis: "am",
      pas: "not",
      pour: "for",
      moi: "myself",
      qui: "who",
      sera: "will be",
    },
  },
  {
    english: "Do not separate yourself from the community.",
    french: "Ne vous séparez pas de la communauté.",
    source: "—The Talmud",
    wordTranslations: {
      ne: "not",
      vous: "yourself",
      séparez: "separate",
      pas: "not",
      de: "from",
      la: "the",
      communauté: "community",
    },
  },
  {
    english: "The world stands on three things: law, worship, and kindness.",
    french: "Le monde repose sur trois choses: la loi, le culte et la bonté.",
    source: "—The Talmud",
    wordTranslations: {
      le: "the",
      monde: "world",
      repose: "stands",
      sur: "on",
      trois: "three",
      choses: "things",
      la: "the",
      loi: "law",
      culte: "worship",
      et: "and",
      bonté: "kindness",
    },
  },
  {
    english: "Whoever saves one life, saves the entire world.",
    french: "Quiconque sauve une vie, sauve le monde entier.",
    source: "—The Talmud",
    wordTranslations: {
      quiconque: "whoever",
      sauve: "saves",
      une: "one",
      vie: "life",
      le: "the",
      monde: "world",
      entier: "entire",
    },
  },
  {
    english: "Say little and do much.",
    french: "Dites peu et faites beaucoup.",
    source: "—The Talmud",
    wordTranslations: { dites: "say", peu: "little", et: "and", faites: "do", beaucoup: "much" },
  },
  {
    english: "Judge every person favorably.",
    french: "Jugez chaque personne favorablement.",
    source: "—The Talmud",
    wordTranslations: { jugez: "judge", chaque: "every", personne: "person", favorablement: "favorably" },
  },
  {
    english: "Silence is a fence around wisdom.",
    french: "Le silence est une clôture autour de la sagesse.",
    source: "—The Talmud",
    wordTranslations: {
      le: "the",
      silence: "silence",
      est: "is",
      une: "a",
      clôture: "fence",
      autour: "around",
      de: "of",
      la: "the",
      sagesse: "wisdom",
    },
  },
  {
    english: "Where there is no vision, the people perish.",
    french: "Là où il n'y a pas de vision, les gens périssent.",
    source: "—The Talmud",
    wordTranslations: {
      là: "where",
      où: "where",
      il: "there",
      "n'y": "not",
      a: "is",
      pas: "not",
      de: "of",
      vision: "vision",
      les: "the",
      gens: "people",
      périssent: "perish",
    },
  },
  {
    english: "The highest form of wisdom is kindness.",
    french: "La forme la plus élevée de sagesse est la bonté.",
    source: "—The Talmud",
    wordTranslations: {
      la: "the",
      forme: "form",
      plus: "most",
      élevée: "high",
      de: "of",
      sagesse: "wisdom",
      est: "is",
      bonté: "kindness",
    },
  },
  {
    english: "Do not be daunted by the size of the task.",
    french: "Ne soyez pas découragé par la taille de la tâche.",
    source: "—The Talmud",
    wordTranslations: {
      ne: "not",
      soyez: "be",
      pas: "not",
      découragé: "daunted",
      par: "by",
      la: "the",
      taille: "size",
      de: "of",
      tâche: "task",
    },
  },
  {
    english: "Teach your tongue to say I do not know.",
    french: "Apprenez à votre langue à dire je ne sais pas.",
    source: "—The Talmud",
    wordTranslations: {
      apprenez: "teach",
      à: "to",
      votre: "your",
      langue: "tongue",
      dire: "say",
      je: "I",
      ne: "not",
      sais: "know",
      pas: "not",
    },
  },
  {
    english: "Who is mighty? One who controls their impulses.",
    french: "Qui est puissant? Celui qui contrôle ses impulsions.",
    source: "—The Talmud",
    wordTranslations: {
      qui: "who",
      est: "is",
      puissant: "mighty",
      celui: "one",
      contrôle: "controls",
      ses: "their",
      impulsions: "impulses",
    },
  },
  {
    english: "It is not your duty to finish the work, but neither are you free to desist from it.",
    french: "Ce n'est pas votre devoir de finir le travail, mais vous n'êtes pas non plus libre de vous en abstenir.",
    source: "—The Talmud",
    wordTranslations: {
      ce: "it",
      "n'est": "is not",
      pas: "not",
      votre: "your",
      devoir: "duty",
      de: "to",
      finir: "finish",
      le: "the",
      travail: "work",
      mais: "but",
      vous: "you",
      êtes: "are",
      non: "neither",
      plus: "more",
      libre: "free",
      en: "from it",
      abstenir: "desist",
    },
  },
  {
    english: "Make your books your companions.",
    french: "Faites de vos livres vos compagnons.",
    source: "—The Talmud",
    wordTranslations: { faites: "make", de: "of", vos: "your", livres: "books", compagnons: "companions" },
  },
  {
    english: "A person should always be humble like a reed.",
    french: "Une personne doit toujours être humble comme un roseau.",
    source: "—The Talmud",
    wordTranslations: {
      une: "a",
      personne: "person",
      doit: "should",
      toujours: "always",
      être: "be",
      humble: "humble",
      comme: "like",
      un: "a",
      roseau: "reed",
    },
  },
  {
    english: "The day is short, and the work is much.",
    french: "Le jour est court, et le travail est beaucoup.",
    source: "—The Talmud",
    wordTranslations: {
      le: "the",
      jour: "day",
      est: "is",
      court: "short",
      et: "and",
      travail: "work",
      beaucoup: "much",
    },
  },
  {
    english: "Greater is hospitality than receiving the Divine Presence.",
    french: "Plus grande est l'hospitalité que de recevoir la Présence Divine.",
    source: "—The Talmud",
    wordTranslations: {
      plus: "more",
      grande: "great",
      est: "is",
      "l'hospitalité": "hospitality",
      que: "than",
      de: "of",
      recevoir: "receiving",
      la: "the",
      présence: "presence",
      divine: "divine",
    },
  },
  {
    english: "Who is rich? One who is happy with their portion.",
    french: "Qui est riche? Celui qui est heureux de sa part.",
    source: "—The Talmud",
    wordTranslations: {
      qui: "who",
      est: "is",
      riche: "rich",
      celui: "one",
      heureux: "happy",
      de: "with",
      sa: "their",
      part: "portion",
    },
  },

  // US Bill of Rights (5)
  {
    english: "Congress shall make no law abridging freedom of speech.",
    french: "Le Congrès ne fera aucune loi abrégeant la liberté d'expression.",
    source: "—US Bill of Rights",
    wordTranslations: {
      le: "the",
      congrès: "congress",
      ne: "not",
      fera: "shall make",
      aucune: "no",
      loi: "law",
      abrégeant: "abridging",
      la: "the",
      liberté: "freedom",
      "d'expression": "of speech",
    },
  },
  {
    english: "The right of the people to keep and bear arms shall not be infringed.",
    french: "Le droit du peuple de garder et de porter des armes ne sera pas enfreint.",
    source: "—US Bill of Rights",
    wordTranslations: {
      le: "the",
      droit: "right",
      du: "of the",
      peuple: "people",
      de: "to",
      garder: "keep",
      et: "and",
      porter: "bear",
      des: "of",
      armes: "arms",
      ne: "not",
      sera: "shall",
      pas: "not",
      enfreint: "infringed",
    },
  },
  {
    english: "No person shall be deprived of life, liberty, or property without due process.",
    french: "Aucune personne ne sera privée de vie, de liberté ou de propriété sans procédure régulière.",
    source: "—US Bill of Rights",
    wordTranslations: {
      aucune: "no",
      personne: "person",
      ne: "not",
      sera: "shall be",
      privée: "deprived",
      de: "of",
      vie: "life",
      liberté: "liberty",
      ou: "or",
      propriété: "property",
      sans: "without",
      procédure: "process",
      régulière: "due",
    },
  },
  {
    english: "The right to a speedy and public trial shall be preserved.",
    french: "Le droit à un procès rapide et public sera préservé.",
    source: "—US Bill of Rights",
    wordTranslations: {
      le: "the",
      droit: "right",
      à: "to",
      un: "a",
      procès: "trial",
      rapide: "speedy",
      et: "and",
      public: "public",
      sera: "shall be",
      préservé: "preserved",
    },
  },
  {
    english: "Excessive bail shall not be required.",
    french: "Une caution excessive ne sera pas exigée.",
    source: "—US Bill of Rights",
    wordTranslations: {
      une: "a",
      caution: "bail",
      excessive: "excessive",
      ne: "not",
      sera: "shall be",
      pas: "not",
      exigée: "required",
    },
  },

  // US Declaration of Independence (5)
  {
    english: "All men are created equal.",
    french: "Tous les hommes sont créés égaux.",
    source: "—US Declaration of Independence",
    wordTranslations: { tous: "all", les: "the", hommes: "men", sont: "are", créés: "created", égaux: "equal" },
  },
  {
    english: "We hold these truths to be self-evident.",
    french: "Nous tenons ces vérités pour évidentes.",
    source: "—US Declaration of Independence",
    wordTranslations: {
      nous: "we",
      tenons: "hold",
      ces: "these",
      vérités: "truths",
      pour: "to be",
      évidentes: "self-evident",
    },
  },
  {
    english: "Life, liberty, and the pursuit of happiness.",
    french: "La vie, la liberté et la poursuite du bonheur.",
    source: "—US Declaration of Independence",
    wordTranslations: {
      la: "the",
      vie: "life",
      liberté: "liberty",
      et: "and",
      poursuite: "pursuit",
      du: "of",
      bonheur: "happiness",
    },
  },
  {
    english: "Governments derive their powers from the consent of the governed.",
    french: "Les gouvernements tirent leurs pouvoirs du consentement des gouvernés.",
    source: "—US Declaration of Independence",
    wordTranslations: {
      les: "the",
      gouvernements: "governments",
      tirent: "derive",
      leurs: "their",
      pouvoirs: "powers",
      du: "from the",
      consentement: "consent",
      des: "of the",
      gouvernés: "governed",
    },
  },
  {
    english: "When tyranny becomes law, rebellion becomes duty.",
    french: "Quand la tyrannie devient loi, la rébellion devient devoir.",
    source: "—US Declaration of Independence",
    wordTranslations: {
      quand: "when",
      la: "the",
      tyrannie: "tyranny",
      devient: "becomes",
      loi: "law",
      rébellion: "rebellion",
      devoir: "duty",
    },
  },

  // Mao's Little Red Book (10)
  {
    english: "A revolution is not a dinner party.",
    french: "Une révolution n'est pas un dîner.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      une: "a",
      révolution: "revolution",
      "n'est": "is not",
      pas: "not",
      un: "a",
      dîner: "dinner party",
    },
  },
  {
    english: "Political power grows out of the barrel of a gun.",
    french: "Le pouvoir politique naît du canon d'un fusil.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      le: "the",
      pouvoir: "power",
      politique: "political",
      naît: "grows",
      du: "out of",
      canon: "barrel",
      "d'un": "of a",
      fusil: "gun",
    },
  },
  {
    english: "Let a hundred flowers bloom.",
    french: "Laissez cent fleurs s'épanouir.",
    source: "—Mao's Little Red Book",
    wordTranslations: { laissez: "let", cent: "hundred", fleurs: "flowers", "s'épanouir": "bloom" },
  },
  {
    english: "Serve the people.",
    french: "Servez le peuple.",
    source: "—Mao's Little Red Book",
    wordTranslations: { servez: "serve", le: "the", peuple: "people" },
  },
  {
    english: "Practice Marxism, not revisionism.",
    french: "Pratiquez le marxisme, pas le révisionnisme.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      pratiquez: "practice",
      le: "the",
      marxisme: "marxism",
      pas: "not",
      révisionnisme: "revisionism",
    },
  },
  {
    english: "Be resolute, fear no sacrifice.",
    french: "Soyez résolu, ne craignez aucun sacrifice.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      soyez: "be",
      résolu: "resolute",
      ne: "not",
      craignez: "fear",
      aucun: "no",
      sacrifice: "sacrifice",
    },
  },
  {
    english: "Everything under heaven is in chaos, the situation is excellent.",
    french: "Tout sous le ciel est en chaos, la situation est excellente.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      tout: "everything",
      sous: "under",
      le: "the",
      ciel: "heaven",
      est: "is",
      en: "in",
      chaos: "chaos",
      la: "the",
      situation: "situation",
      excellente: "excellent",
    },
  },
  {
    english: "To read too many books is harmful.",
    french: "Lire trop de livres est nuisible.",
    source: "—Mao's Little Red Book",
    wordTranslations: { lire: "to read", trop: "too", de: "of", livres: "books", est: "is", nuisible: "harmful" },
  },
  {
    english: "Women hold up half the sky.",
    french: "Les femmes soutiennent la moitié du ciel.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      les: "the",
      femmes: "women",
      soutiennent: "hold up",
      la: "the",
      moitié: "half",
      du: "of the",
      ciel: "sky",
    },
  },
  {
    english: "The people, and the people alone, are the motive force.",
    french: "Le peuple, et le peuple seul, est la force motrice.",
    source: "—Mao's Little Red Book",
    wordTranslations: {
      le: "the",
      peuple: "people",
      et: "and",
      seul: "alone",
      est: "is",
      la: "the",
      force: "force",
      motrice: "motive",
    },
  },

  // Confucius (10)
  {
    english: "It does not matter how slowly you go as long as you do not stop.",
    french: "Peu importe la lenteur avec laquelle vous allez tant que vous ne vous arrêtez pas.",
    source: "—Confucius",
    wordTranslations: {
      peu: "not",
      importe: "matter",
      la: "the",
      lenteur: "slowly",
      avec: "with",
      laquelle: "which",
      vous: "you",
      allez: "go",
      tant: "as long",
      que: "as",
      ne: "not",
      arrêtez: "stop",
      pas: "not",
    },
  },
  {
    english: "Our greatest glory is not in never falling, but in rising every time we fall.",
    french:
      "Notre plus grande gloire n'est pas de ne jamais tomber, mais de nous relever chaque fois que nous tombons.",
    source: "—Confucius",
    wordTranslations: {
      notre: "our",
      plus: "most",
      grande: "great",
      gloire: "glory",
      "n'est": "is not",
      pas: "not",
      de: "in",
      ne: "not",
      jamais: "never",
      tomber: "falling",
      mais: "but",
      nous: "we",
      relever: "rising",
      chaque: "every",
      fois: "time",
      tombons: "fall",
    },
  },
  {
    english: "Choose a job you love, and you will never work a day.",
    french: "Choisissez un travail que vous aimez, et vous ne travaillerez jamais un jour.",
    source: "—Confucius",
    wordTranslations: {
      choisissez: "choose",
      un: "a",
      travail: "job",
      que: "that",
      vous: "you",
      aimez: "love",
      et: "and",
      ne: "not",
      travaillerez: "will work",
      jamais: "never",
      jour: "day",
    },
  },
  {
    english: "The man who moves a mountain begins by carrying away small stones.",
    french: "L'homme qui déplace une montagne commence par transporter de petites pierres.",
    source: "—Confucius",
    wordTranslations: {
      "l'homme": "the man",
      qui: "who",
      déplace: "moves",
      une: "a",
      montagne: "mountain",
      commence: "begins",
      par: "by",
      transporter: "carrying",
      de: "of",
      petites: "small",
      pierres: "stones",
    },
  },
  {
    english: "Respect yourself and others will respect you.",
    french: "Respectez-vous et les autres vous respecteront.",
    source: "—Confucius",
    wordTranslations: {
      "respectez-vous": "respect yourself",
      et: "and",
      les: "the",
      autres: "others",
      vous: "you",
      respecteront: "will respect",
    },
  },
  {
    english: "Wherever you go, go with all your heart.",
    french: "Où que vous alliez, allez-y de tout votre cœur.",
    source: "—Confucius",
    wordTranslations: {
      où: "where",
      que: "that",
      vous: "you",
      alliez: "go",
      "allez-y": "go",
      de: "with",
      tout: "all",
      votre: "your",
      cœur: "heart",
    },
  },
  {
    english: "Real knowledge is to know the extent of one's ignorance.",
    french: "La vraie connaissance est de connaître l'étendue de son ignorance.",
    source: "—Confucius",
    wordTranslations: {
      la: "the",
      vraie: "real",
      connaissance: "knowledge",
      est: "is",
      de: "to",
      connaître: "know",
      "l'étendue": "extent",
      de: "of",
      son: "one's",
      ignorance: "ignorance",
    },
  },
  {
    english: "When anger rises, think of the consequences.",
    french: "Quand la colère monte, pensez aux conséquences.",
    source: "—Confucius",
    wordTranslations: {
      quand: "when",
      la: "the",
      colère: "anger",
      monte: "rises",
      pensez: "think",
      aux: "of the",
      conséquences: "consequences",
    },
  },
  {
    english: "Silence is a true friend who never betrays.",
    french: "Le silence est un véritable ami qui ne trahit jamais.",
    source: "—Confucius",
    wordTranslations: {
      le: "the",
      silence: "silence",
      est: "is",
      un: "a",
      véritable: "true",
      ami: "friend",
      qui: "who",
      ne: "not",
      trahit: "betrays",
      jamais: "never",
    },
  },
  {
    english: "The will to win, the desire to succeed, the urge to reach your full potential.",
    french: "La volonté de gagner, le désir de réussir, l'envie d'atteindre votre plein potentiel.",
    source: "—Confucius",
    wordTranslations: {
      la: "the",
      volonté: "will",
      de: "to",
      gagner: "win",
      le: "the",
      désir: "desire",
      réussir: "succeed",
      "l'envie": "urge",
      "d'atteindre": "to reach",
      votre: "your",
      plein: "full",
      potentiel: "potential",
    },
  },

  // Karl Marx (5)
  {
    english: "Workers of the world, unite!",
    french: "Travailleurs du monde, unissez-vous!",
    source: "—Karl Marx",
    wordTranslations: { travailleurs: "workers", du: "of the", monde: "world", "unissez-vous": "unite" },
  },
  {
    english: "From each according to his ability, to each according to his needs.",
    french: "De chacun selon ses capacités, à chacun selon ses besoins.",
    source: "—Karl Marx",
    wordTranslations: {
      de: "from",
      chacun: "each",
      selon: "according to",
      ses: "his",
      capacités: "ability",
      à: "to",
      besoins: "needs",
    },
  },
  {
    english: "History repeats itself, first as tragedy, second as farce.",
    french: "L'histoire se répète, d'abord comme tragédie, ensuite comme farce.",
    source: "—Karl Marx",
    wordTranslations: {
      "l'histoire": "history",
      se: "itself",
      répète: "repeats",
      "d'abord": "first",
      comme: "as",
      tragédie: "tragedy",
      ensuite: "second",
      farce: "farce",
    },
  },
  {
    english: "The philosophers have only interpreted the world; the point is to change it.",
    french: "Les philosophes n'ont fait qu'interpréter le monde; le but est de le changer.",
    source: "—Karl Marx",
    wordTranslations: {
      les: "the",
      philosophes: "philosophers",
      "n'ont": "have",
      fait: "only",
      "qu'interpréter": "interpreted",
      le: "the",
      monde: "world",
      but: "point",
      est: "is",
      de: "to",
      changer: "change",
    },
  },
  {
    english: "Religion is the opium of the people.",
    french: "La religion est l'opium du peuple.",
    source: "—Karl Marx",
    wordTranslations: {
      la: "the",
      religion: "religion",
      est: "is",
      "l'opium": "opium",
      du: "of the",
      peuple: "people",
    },
  },

  // Vladimir Lenin (8)
  {
    english: "Give us the child for eight years and it will be a Bolshevik forever.",
    french: "Donnez-nous l'enfant pendant huit ans et il sera bolchevik pour toujours.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      "donnez-nous": "give us",
      "l'enfant": "the child",
      pendant: "for",
      huit: "eight",
      ans: "years",
      et: "and",
      il: "it",
      sera: "will be",
      bolchevik: "bolshevik",
      pour: "for",
      toujours: "forever",
    },
  },
  {
    english: "A lie told often enough becomes the truth.",
    french: "Un mensonge répété assez souvent devient la vérité.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      un: "a",
      mensonge: "lie",
      répété: "told",
      assez: "enough",
      souvent: "often",
      devient: "becomes",
      la: "the",
      vérité: "truth",
    },
  },
  {
    english: "There are no morals in politics, there is only expedience.",
    french: "Il n'y a pas de morale en politique, il n'y a que l'opportunisme.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      il: "there",
      "n'y": "not",
      a: "are",
      pas: "not",
      de: "of",
      morale: "morals",
      en: "in",
      politique: "politics",
      que: "only",
      "l'opportunisme": "expedience",
    },
  },
  {
    english: "The goal of socialism is communism.",
    french: "Le but du socialisme est le communisme.",
    source: "—Vladimir Lenin",
    wordTranslations: { le: "the", but: "goal", du: "of", socialisme: "socialism", est: "is", communisme: "communism" },
  },
  {
    english: "Freedom in capitalist society always remains about the same as it was in ancient Greece.",
    french: "La liberté dans la société capitaliste reste toujours à peu près la même qu'en Grèce antique.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      la: "the",
      liberté: "freedom",
      dans: "in",
      société: "society",
      capitaliste: "capitalist",
      reste: "remains",
      toujours: "always",
      à: "about",
      peu: "about",
      près: "same",
      même: "same",
      "qu'en": "as in",
      grèce: "greece",
      antique: "ancient",
    },
  },
  {
    english: "It is true that liberty is precious, so precious that it must be rationed.",
    french: "Il est vrai que la liberté est précieuse, si précieuse qu'elle doit être rationnée.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      il: "it",
      est: "is",
      vrai: "true",
      que: "that",
      la: "the",
      liberté: "liberty",
      précieuse: "precious",
      si: "so",
      "qu'elle": "it",
      doit: "must",
      être: "be",
      rationnée: "rationed",
    },
  },
  {
    english: "Give me four years to teach the children and the seed I have sown will never be uprooted.",
    french: "Donnez-moi quatre ans pour enseigner aux enfants et la graine que j'ai semée ne sera jamais déracinée.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      "donnez-moi": "give me",
      quatre: "four",
      ans: "years",
      pour: "to",
      enseigner: "teach",
      aux: "the",
      enfants: "children",
      et: "and",
      la: "the",
      graine: "seed",
      que: "that",
      "j'ai": "I have",
      semée: "sown",
      ne: "not",
      sera: "will be",
      jamais: "never",
      déracinée: "uprooted",
    },
  },
  {
    english:
      "The press should be not only a collective propagandist and a collective agitator, but also a collective organizer.",
    french:
      "La presse ne devrait pas être seulement un propagandiste collectif et un agitateur collectif, mais aussi un organisateur collectif.",
    source: "—Vladimir Lenin",
    wordTranslations: {
      la: "the",
      presse: "press",
      ne: "not",
      devrait: "should",
      pas: "not",
      être: "be",
      seulement: "only",
      un: "a",
      propagandiste: "propagandist",
      collectif: "collective",
      et: "and",
      agitateur: "agitator",
      mais: "but",
      aussi: "also",
      organisateur: "organizer",
    },
  },

  // Albert Einstein (5)
  {
    english: "Imagination is more important than knowledge.",
    french: "L'imagination est plus importante que la connaissance.",
    source: "—Albert Einstein",
    wordTranslations: {
      "l'imagination": "imagination",
      est: "is",
      plus: "more",
      importante: "important",
      que: "than",
      la: "the",
      connaissance: "knowledge",
    },
  },
  {
    english: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    french: "La vie est comme faire du vélo. Pour garder l'équilibre, vous devez continuer à bouger.",
    source: "—Albert Einstein",
    wordTranslations: {
      la: "the",
      vie: "life",
      est: "is",
      comme: "like",
      faire: "riding",
      du: "of",
      vélo: "bicycle",
      pour: "to",
      garder: "keep",
      "l'équilibre": "balance",
      vous: "you",
      devez: "must",
      continuer: "keep",
      à: "to",
      bouger: "moving",
    },
  },
  {
    english: "The only source of knowledge is experience.",
    french: "La seule source de connaissance est l'expérience.",
    source: "—Albert Einstein",
    wordTranslations: {
      la: "the",
      seule: "only",
      source: "source",
      de: "of",
      connaissance: "knowledge",
      est: "is",
      "l'expérience": "experience",
    },
  },
  {
    english: "In the middle of difficulty lies opportunity.",
    french: "Au milieu de la difficulté se trouve l'opportunité.",
    source: "—Albert Einstein",
    wordTranslations: {
      au: "in",
      milieu: "middle",
      de: "of",
      la: "the",
      difficulté: "difficulty",
      se: "itself",
      trouve: "lies",
      "l'opportunité": "opportunity",
    },
  },
  {
    english: "Try not to become a person of success, but rather a person of value.",
    french: "Essayez de ne pas devenir une personne de succès, mais plutôt une personne de valeur.",
    source: "—Albert Einstein",
    wordTranslations: {
      essayez: "try",
      de: "to",
      ne: "not",
      pas: "not",
      devenir: "become",
      une: "a",
      personne: "person",
      succès: "success",
      mais: "but",
      plutôt: "rather",
      valeur: "value",
    },
  },

  // Humorous observations (20)
  {
    english: "I intend to live forever. So far, so good.",
    french: "J'ai l'intention de vivre éternellement. Jusqu'ici, tout va bien.",
    source: "—Humorous Observation",
    wordTranslations: {
      "j'ai": "I have",
      "l'intention": "intention",
      de: "to",
      vivre: "live",
      éternellement: "forever",
      "jusqu'ici": "so far",
      tout: "all",
      va: "goes",
      bien: "good",
    },
  },
  {
    english: "The early bird gets the worm, but the second mouse gets the cheese.",
    french: "L'oiseau matinal attrape le ver, mais la deuxième souris attrape le fromage.",
    source: "—Humorous Observation",
    wordTranslations: {
      "l'oiseau": "bird",
      matinal: "early",
      attrape: "gets",
      le: "the",
      ver: "worm",
      mais: "but",
      la: "the",
      deuxième: "second",
      souris: "mouse",
      fromage: "cheese",
    },
  },
  {
    english: "If at first you don't succeed, then skydiving definitely isn't for you.",
    french: "Si au début vous ne réussissez pas, alors le parachutisme n'est définitivement pas pour vous.",
    source: "—Humorous Observation",
    wordTranslations: {
      si: "if",
      au: "at",
      début: "first",
      vous: "you",
      ne: "not",
      réussissez: "succeed",
      pas: "not",
      alors: "then",
      le: "the",
      parachutisme: "skydiving",
      "n'est": "is not",
      définitivement: "definitely",
      pour: "for",
    },
  },
  {
    english: "I'm not lazy, I'm just on energy-saving mode.",
    french: "Je ne suis pas paresseux, je suis juste en mode économie d'énergie.",
    source: "—Humorous Observation",
    wordTranslations: {
      je: "I",
      ne: "not",
      suis: "am",
      pas: "not",
      paresseux: "lazy",
      juste: "just",
      en: "on",
      mode: "mode",
      économie: "saving",
      "d'énergie": "energy",
    },
  },
  {
    english: "Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad.",
    french:
      "La connaissance c'est savoir qu'une tomate est un fruit; la sagesse c'est ne pas la mettre dans une salade de fruits.",
    source: "—Humorous Observation",
    wordTranslations: {
      la: "the",
      connaissance: "knowledge",
      "c'est": "is",
      savoir: "knowing",
      "qu'une": "a",
      tomate: "tomato",
      est: "is",
      un: "a",
      fruit: "fruit",
      sagesse: "wisdom",
      ne: "not",
      pas: "not",
      mettre: "putting",
      dans: "in",
      une: "a",
      salade: "salad",
      de: "of",
      fruits: "fruit",
    },
  },
  {
    english: "Common sense is like deodorant. The people who need it most never use it.",
    french: "Le bon sens est comme le déodorant. Les gens qui en ont le plus besoin ne l'utilisent jamais.",
    source: "—Humorous Observation",
    wordTranslations: {
      le: "the",
      bon: "common",
      sens: "sense",
      est: "is",
      comme: "like",
      déodorant: "deodorant",
      les: "the",
      gens: "people",
      qui: "who",
      en: "it",
      ont: "need",
      plus: "most",
      besoin: "need",
      ne: "not",
      "l'utilisent": "use",
      jamais: "never",
    },
  },
  {
    english: "I asked God for a bike, but I know God doesn't work that way.",
    french: "J'ai demandé à Dieu un vélo, mais je sais que Dieu ne fonctionne pas comme ça.",
    source: "—Humorous Observation",
    wordTranslations: {
      "j'ai": "I",
      demandé: "asked",
      à: "to",
      dieu: "god",
      un: "a",
      vélo: "bike",
      mais: "but",
      je: "I",
      sais: "know",
      que: "that",
      ne: "not",
      fonctionne: "work",
      pas: "not",
      comme: "that",
      ça: "way",
    },
  },
  {
    english: "The problem with troubleshooting is that trouble shoots back.",
    french: "Le problème avec le dépannage est que les ennuis ripostent.",
    source: "—Humorous Observation",
    wordTranslations: {
      le: "the",
      problème: "problem",
      avec: "with",
      dépannage: "troubleshooting",
      est: "is",
      que: "that",
      les: "the",
      ennuis: "trouble",
      ripostent: "shoots back",
    },
  },
  {
    english: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    french: "J'ai dit à ma femme qu'elle dessinait ses sourcils trop haut. Elle a eu l'air surprise.",
    source: "—Humorous Observation",
    wordTranslations: {
      "j'ai": "I",
      dit: "told",
      à: "to",
      ma: "my",
      femme: "wife",
      "qu'elle": "she",
      dessinait: "was drawing",
      ses: "her",
      sourcils: "eyebrows",
      trop: "too",
      haut: "high",
      elle: "she",
      a: "has",
      eu: "had",
      "l'air": "looked",
      surprise: "surprised",
    },
  },
  {
    english: "My bed is a magical place where I suddenly remember everything I forgot to do.",
    french: "Mon lit est un endroit magique où je me souviens soudain de tout ce que j'ai oublié de faire.",
    source: "—Humorous Observation",
    wordTranslations: {
      mon: "my",
      lit: "bed",
      est: "is",
      un: "a",
      endroit: "place",
      magique: "magical",
      où: "where",
      je: "I",
      me: "myself",
      souviens: "remember",
      soudain: "suddenly",
      de: "of",
      tout: "everything",
      ce: "that",
      que: "that",
      "j'ai": "I",
      oublié: "forgot",
      faire: "do",
    },
  },
  {
    english: "I'm not arguing, I'm just explaining why I'm right.",
    french: "Je ne discute pas, j'explique juste pourquoi j'ai raison.",
    source: "—Humorous Observation",
    wordTranslations: {
      je: "I",
      ne: "not",
      discute: "arguing",
      pas: "not",
      "j'explique": "explaining",
      juste: "just",
      pourquoi: "why",
      "j'ai": "I'm",
      raison: "right",
    },
  },
  {
    english: "If you think nobody cares if you're alive, try missing a couple of payments.",
    french: "Si vous pensez que personne ne se soucie si vous êtes vivant, essayez de manquer quelques paiements.",
    source: "—Humorous Observation",
    wordTranslations: {
      si: "if",
      vous: "you",
      pensez: "think",
      que: "that",
      personne: "nobody",
      ne: "not",
      se: "cares",
      soucie: "cares",
      êtes: "are",
      vivant: "alive",
      essayez: "try",
      de: "of",
      manquer: "missing",
      quelques: "couple",
      paiements: "payments",
    },
  },
  {
    english: "The quickest way to double your money is to fold it in half.",
    french: "Le moyen le plus rapide de doubler votre argent est de le plier en deux.",
    source: "—Humorous Observation",
    wordTranslations: {
      le: "the",
      moyen: "way",
      plus: "most",
      rapide: "quick",
      de: "to",
      doubler: "double",
      votre: "your",
      argent: "money",
      est: "is",
      plier: "fold",
      en: "in",
      deux: "half",
    },
  },
  {
    english: "A clear conscience is usually the sign of a bad memory.",
    french: "Une conscience claire est généralement le signe d'une mauvaise mémoire.",
    source: "—Humorous Observation",
    wordTranslations: {
      une: "a",
      conscience: "conscience",
      claire: "clear",
      est: "is",
      généralement: "usually",
      le: "the",
      signe: "sign",
      "d'une": "of a",
      mauvaise: "bad",
      mémoire: "memory",
    },
  },
  {
    english: "Always borrow money from a pessimist. He won't expect it back.",
    french: "Empruntez toujours de l'argent à un pessimiste. Il ne s'attendra pas à le récupérer.",
    source: "—Humorous Observation",
    wordTranslations: {
      empruntez: "borrow",
      toujours: "always",
      de: "of",
      "l'argent": "money",
      à: "from",
      un: "a",
      pessimiste: "pessimist",
      il: "he",
      ne: "not",
      "s'attendra": "expect",
      pas: "not",
      à: "to",
      le: "it",
      récupérer: "back",
    },
  },
  {
    english: "Change is inevitable, except from a vending machine.",
    french: "Le changement est inévitable, sauf d'un distributeur automatique.",
    source: "—Humorous Observation",
    wordTranslations: {
      le: "the",
      changement: "change",
      est: "is",
      inévitable: "inevitable",
      sauf: "except",
      "d'un": "from a",
      distributeur: "vending",
      automatique: "machine",
    },
  },
  {
    english: "Going to church doesn't make you a Christian any more than standing in a garage makes you a car.",
    french:
      "Aller à l'église ne fait pas de vous un chrétien, pas plus que se tenir dans un garage ne fait de vous une voiture.",
    source: "—Humorous Observation",
    wordTranslations: {
      aller: "going",
      à: "to",
      "l'église": "church",
      ne: "not",
      fait: "make",
      pas: "not",
      de: "of",
      vous: "you",
      un: "a",
      chrétien: "christian",
      plus: "more",
      que: "than",
      se: "standing",
      tenir: "standing",
      dans: "in",
      garage: "garage",
      voiture: "car",
    },
  },
  {
    english: "Light travels faster than sound. That's why some people appear bright until you hear them speak.",
    french:
      "La lumière voyage plus vite que le son. C'est pourquoi certaines personnes semblent brillantes jusqu'à ce que vous les entendiez parler.",
    source: "—Humorous Observation",
    wordTranslations: {
      la: "the",
      lumière: "light",
      voyage: "travels",
      plus: "more",
      vite: "fast",
      que: "than",
      le: "the",
      son: "sound",
      "c'est": "that's",
      pourquoi: "why",
      certaines: "some",
      personnes: "people",
      semblent: "appear",
      brillantes: "bright",
      "jusqu'à": "until",
      ce: "that",
      vous: "you",
      les: "them",
      entendiez: "hear",
      parler: "speak",
    },
  },
  {
    english: "War doesn't determine who's right, only who's left.",
    french: "La guerre ne détermine pas qui a raison, seulement qui reste.",
    source: "—Humorous Observation",
    wordTranslations: {
      la: "the",
      guerre: "war",
      ne: "not",
      détermine: "determine",
      pas: "not",
      qui: "who",
      a: "has",
      raison: "right",
      seulement: "only",
      reste: "left",
    },
  },
  {
    english: "A computer once beat me at chess, but it was no match for me at kickboxing.",
    french: "Un ordinateur m'a battu aux échecs une fois, mais il n'était pas de taille pour moi au kickboxing.",
    source: "—Humorous Observation",
    wordTranslations: {
      un: "a",
      ordinateur: "computer",
      "m'a": "me",
      battu: "beat",
      aux: "at",
      échecs: "chess",
      une: "once",
      fois: "once",
      mais: "but",
      il: "it",
      "n'était": "was not",
      pas: "not",
      de: "of",
      taille: "match",
      pour: "for",
      moi: "me",
      au: "at",
      kickboxing: "kickboxing",
    },
  },

  // Shakespeare (10)
  {
    english: "To be or not to be, that is the question.",
    french: "Être ou ne pas être, telle est la question.",
    source: "—Shakespeare",
    wordTranslations: {
      être: "to be",
      ou: "or",
      ne: "not",
      pas: "not",
      telle: "that",
      est: "is",
      la: "the",
      question: "question",
    },
  },
  {
    english: "All the world's a stage, and all the men and women merely players.",
    french: "Le monde entier est une scène, et tous les hommes et femmes simplement des acteurs.",
    source: "—Shakespeare",
    wordTranslations: {
      le: "the",
      monde: "world",
      entier: "all",
      est: "is",
      une: "a",
      scène: "stage",
      et: "and",
      tous: "all",
      les: "the",
      hommes: "men",
      femmes: "women",
      simplement: "merely",
      des: "of",
      acteurs: "players",
    },
  },
  {
    english: "Love all, trust a few, do wrong to none.",
    french: "Aimez tous, faites confiance à quelques-uns, ne faites de tort à personne.",
    source: "—Shakespeare",
    wordTranslations: {
      aimez: "love",
      tous: "all",
      faites: "do",
      confiance: "trust",
      à: "to",
      "quelques-uns": "few",
      ne: "not",
      de: "of",
      tort: "wrong",
      personne: "none",
    },
  },
  {
    english: "The course of true love never did run smooth.",
    french: "Le cours du véritable amour n'a jamais été sans heurts.",
    source: "—Shakespeare",
    wordTranslations: {
      le: "the",
      cours: "course",
      du: "of",
      véritable: "true",
      amour: "love",
      "n'a": "not",
      jamais: "never",
      été: "did",
      sans: "without",
      heurts: "smooth",
    },
  },
  {
    english: "Cowards die many times before their deaths.",
    french: "Les lâches meurent plusieurs fois avant leur mort.",
    source: "—Shakespeare",
    wordTranslations: {
      les: "the",
      lâches: "cowards",
      meurent: "die",
      plusieurs: "many",
      fois: "times",
      avant: "before",
      leur: "their",
      mort: "deaths",
    },
  },
  {
    english: "Some are born great, some achieve greatness, and some have greatness thrust upon them.",
    french: "Certains naissent grands, certains atteignent la grandeur, et certains se voient imposer la grandeur.",
    source: "—Shakespeare",
    wordTranslations: {
      certains: "some",
      naissent: "are born",
      grands: "great",
      atteignent: "achieve",
      la: "the",
      grandeur: "greatness",
      et: "and",
      se: "themselves",
      voient: "have",
      imposer: "thrust",
      upon: "upon",
    },
  },
  {
    english: "This above all: to thine own self be true.",
    french: "Ceci avant tout: sois fidèle à toi-même.",
    source: "—Shakespeare",
    wordTranslations: {
      ceci: "this",
      avant: "above",
      tout: "all",
      sois: "be",
      fidèle: "true",
      à: "to",
      "toi-même": "own self",
    },
  },
  {
    english: "Though she be but little, she is fierce.",
    french: "Bien qu'elle soit petite, elle est féroce.",
    source: "—Shakespeare",
    wordTranslations: {
      bien: "though",
      "qu'elle": "she",
      soit: "be",
      petite: "little",
      elle: "she",
      est: "is",
      féroce: "fierce",
    },
  },
  {
    english: "We know what we are, but know not what we may be.",
    french: "Nous savons ce que nous sommes, mais ne savons pas ce que nous pouvons être.",
    source: "—Shakespeare",
    wordTranslations: {
      nous: "we",
      savons: "know",
      ce: "what",
      que: "that",
      sommes: "are",
      mais: "but",
      ne: "not",
      pas: "not",
      pouvons: "may",
      être: "be",
    },
  },
  {
    english: "Brevity is the soul of wit.",
    french: "La brièveté est l'âme de l'esprit.",
    source: "—Shakespeare",
    wordTranslations: { la: "the", brièveté: "brevity", est: "is", "l'âme": "soul", de: "of", "l'esprit": "wit" },
  },

  // Mark Twain (10)
  {
    english: "The secret of getting ahead is getting started.",
    french: "Le secret pour avancer est de commencer.",
    source: "—Mark Twain",
    wordTranslations: {
      le: "the",
      secret: "secret",
      pour: "of",
      avancer: "getting ahead",
      est: "is",
      de: "of",
      commencer: "getting started",
    },
  },
  {
    english: "Kindness is the language which the deaf can hear and the blind can see.",
    french: "La gentillesse est la langue que les sourds peuvent entendre et les aveugles peuvent voir.",
    source: "—Mark Twain",
    wordTranslations: {
      la: "the",
      gentillesse: "kindness",
      est: "is",
      langue: "language",
      que: "which",
      les: "the",
      sourds: "deaf",
      peuvent: "can",
      entendre: "hear",
      et: "and",
      aveugles: "blind",
      voir: "see",
    },
  },
  {
    english: "Never put off till tomorrow what may be done day after tomorrow just as well.",
    french: "Ne remettez jamais à demain ce qui peut être fait après-demain tout aussi bien.",
    source: "—Mark Twain",
    wordTranslations: {
      ne: "not",
      remettez: "put off",
      jamais: "never",
      à: "till",
      demain: "tomorrow",
      ce: "what",
      qui: "that",
      peut: "may",
      être: "be",
      fait: "done",
      "après-demain": "day after tomorrow",
      tout: "just",
      aussi: "as",
      bien: "well",
    },
  },
  {
    english: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    french:
      "Chaque fois que vous vous trouvez du côté de la majorité, il est temps de faire une pause et de réfléchir.",
    source: "—Mark Twain",
    wordTranslations: {
      chaque: "whenever",
      fois: "time",
      que: "that",
      vous: "you",
      trouvez: "find",
      du: "on",
      côté: "side",
      de: "of",
      la: "the",
      majorité: "majority",
      il: "it",
      est: "is",
      temps: "time",
      faire: "to",
      une: "a",
      pause: "pause",
      et: "and",
      réfléchir: "reflect",
    },
  },
  {
    english: "The man who does not read has no advantage over the man who cannot read.",
    french: "L'homme qui ne lit pas n'a aucun avantage sur l'homme qui ne peut pas lire.",
    source: "—Mark Twain",
    wordTranslations: {
      "l'homme": "the man",
      qui: "who",
      ne: "not",
      lit: "read",
      pas: "not",
      "n'a": "has not",
      aucun: "no",
      avantage: "advantage",
      sur: "over",
      peut: "can",
      lire: "read",
    },
  },
  {
    english: "If you tell the truth, you don't have to remember anything.",
    french: "Si vous dites la vérité, vous n'avez pas à vous souvenir de quoi que ce soit.",
    source: "—Mark Twain",
    wordTranslations: {
      si: "if",
      vous: "you",
      dites: "tell",
      la: "the",
      vérité: "truth",
      "n'avez": "have not",
      pas: "not",
      à: "to",
      souvenir: "remember",
      de: "of",
      quoi: "anything",
      que: "that",
      ce: "this",
      soit: "is",
    },
  },
  {
    english: "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    french: "De bons amis, de bons livres et une conscience endormie: c'est la vie idéale.",
    source: "—Mark Twain",
    wordTranslations: {
      de: "of",
      bons: "good",
      amis: "friends",
      livres: "books",
      et: "and",
      une: "a",
      conscience: "conscience",
      endormie: "sleepy",
      "c'est": "this is",
      la: "the",
      vie: "life",
      idéale: "ideal",
    },
  },
  {
    english: "Keep away from people who try to belittle your ambitions.",
    french: "Tenez-vous à l'écart des gens qui essaient de rabaisser vos ambitions.",
    source: "—Mark Twain",
    wordTranslations: {
      "tenez-vous": "keep",
      à: "to",
      "l'écart": "away",
      des: "from",
      gens: "people",
      qui: "who",
      essaient: "try",
      de: "to",
      rabaisser: "belittle",
      vos: "your",
      ambitions: "ambitions",
    },
  },
  {
    english: "It's not the size of the dog in the fight, it's the size of the fight in the dog.",
    french: "Ce n'est pas la taille du chien dans le combat, c'est la taille du combat dans le chien.",
    source: "—Mark Twain",
    wordTranslations: {
      ce: "it",
      "n'est": "is not",
      pas: "not",
      la: "the",
      taille: "size",
      du: "of the",
      chien: "dog",
      dans: "in",
      le: "the",
      combat: "fight",
    },
  },
  {
    english: "The two most important days in your life are the day you are born and the day you find out why.",
    french:
      "Les deux jours les plus importants de votre vie sont le jour où vous êtes né et le jour où vous découvrez pourquoi.",
    source: "—Mark Twain",
    wordTranslations: {
      les: "the",
      deux: "two",
      jours: "days",
      plus: "most",
      importants: "important",
      de: "in",
      votre: "your",
      vie: "life",
      sont: "are",
      le: "the",
      jour: "day",
      où: "when",
      vous: "you",
      êtes: "are",
      né: "born",
      et: "and",
      découvrez: "find out",
      pourquoi: "why",
    },
  },

  // Winston Churchill (5)
  {
    english: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    french: "Le succès n'est pas final, l'échec n'est pas fatal: c'est le courage de continuer qui compte.",
    source: "—Winston Churchill",
    wordTranslations: {
      le: "the",
      succès: "success",
      "n'est": "is not",
      pas: "not",
      final: "final",
      "l'échec": "failure",
      fatal: "fatal",
      "c'est": "it is",
      courage: "courage",
      de: "to",
      continuer: "continue",
      qui: "that",
      compte: "counts",
    },
  },
  {
    english: "We make a living by what we get, but we make a life by what we give.",
    french: "Nous gagnons notre vie par ce que nous obtenons, mais nous faisons une vie par ce que nous donnons.",
    source: "—Winston Churchill",
    wordTranslations: {
      nous: "we",
      gagnons: "make",
      notre: "our",
      vie: "living",
      par: "by",
      ce: "what",
      que: "that",
      obtenons: "get",
      mais: "but",
      faisons: "make",
      une: "a",
      donnons: "give",
    },
  },
  {
    english: "Never, never, never give up.",
    french: "Ne jamais, jamais, jamais abandonner.",
    source: "—Winston Churchill",
    wordTranslations: { ne: "not", jamais: "never", abandonner: "give up" },
  },
  {
    english: "Attitude is a little thing that makes a big difference.",
    french: "L'attitude est une petite chose qui fait une grande différence.",
    source: "—Winston Churchill",
    wordTranslations: {
      "l'attitude": "attitude",
      est: "is",
      une: "a",
      petite: "little",
      chose: "thing",
      qui: "that",
      fait: "makes",
      grande: "big",
      différence: "difference",
    },
  },
  {
    english: "If you're going through hell, keep going.",
    french: "Si vous traversez l'enfer, continuez.",
    source: "—Winston Churchill",
    wordTranslations: { si: "if", vous: "you", traversez: "going through", "l'enfer": "hell", continuez: "keep going" },
  },

  // Oscar Wilde (5)
  {
    english: "Be yourself; everyone else is already taken.",
    french: "Soyez vous-même; tout le monde est déjà pris.",
    source: "—Oscar Wilde",
    wordTranslations: {
      soyez: "be",
      "vous-même": "yourself",
      tout: "everyone",
      le: "the",
      monde: "else",
      est: "is",
      déjà: "already",
      pris: "taken",
    },
  },
  {
    english: "To live is the rarest thing in the world. Most people exist, that is all.",
    french: "Vivre est la chose la plus rare au monde. La plupart des gens existent, c'est tout.",
    source: "—Oscar Wilde",
    wordTranslations: {
      vivre: "to live",
      est: "is",
      la: "the",
      chose: "thing",
      plus: "most",
      rare: "rare",
      au: "in the",
      monde: "world",
      plupart: "most",
      des: "of",
      gens: "people",
      existent: "exist",
      "c'est": "that is",
      tout: "all",
    },
  },
  {
    english: "I can resist everything except temptation.",
    french: "Je peux résister à tout sauf à la tentation.",
    source: "—Oscar Wilde",
    wordTranslations: {
      je: "I",
      peux: "can",
      résister: "resist",
      à: "to",
      tout: "everything",
      sauf: "except",
      la: "the",
      tentation: "temptation",
    },
  },
  {
    english: "Always forgive your enemies; nothing annoys them so much.",
    french: "Pardonnez toujours à vos ennemis; rien ne les ennuie autant.",
    source: "—Oscar Wilde",
    wordTranslations: {
      pardonnez: "forgive",
      toujours: "always",
      à: "to",
      vos: "your",
      ennemis: "enemies",
      rien: "nothing",
      ne: "not",
      les: "them",
      ennuie: "annoys",
      autant: "so much",
    },
  },
  {
    english: "We are all in the gutter, but some of us are looking at the stars.",
    french: "Nous sommes tous dans le caniveau, mais certains d'entre nous regardent les étoiles.",
    source: "—Oscar Wilde",
    wordTranslations: {
      nous: "we",
      sommes: "are",
      tous: "all",
      dans: "in",
      le: "the",
      caniveau: "gutter",
      mais: "but",
      certains: "some",
      "d'entre": "of",
      nous: "us",
      regardent: "looking at",
      les: "the",
      étoiles: "stars",
    },
  },
]
